/* Generated by JTB 1.4.4 */
package parsers.multistateSpecies.syntaxtree;

import parsers.multistateSpecies.visitor.*;

/**
 * JTB node class for the production MultistateSpecies_SingleStateDefinition:<br>
 * Corresponding grammar :<br>
 * multistateSpecies_SiteName -> MultistateSpecies_SiteName()<br>
 * nodeToken -> < OPEN_C ><br>
 * multistateSpecies_SiteSingleElement -> MultistateSpecies_SiteSingleElement()<br>
 * nodeListOptional -> ( #0 < SITE_STATES_SEPARATOR > #1 MultistateSpecies_SiteSingleElement() )*<br>
 * nodeToken1 -> < CLOSED_C ><br>
 */
public class MultistateSpecies_SingleStateDefinition implements INode {

  /** A child node */
  public MultistateSpecies_SiteName multistateSpecies_SiteName;

  /** A child node */
  public NodeToken nodeToken;

  /** A child node */
  public MultistateSpecies_SiteSingleElement multistateSpecies_SiteSingleElement;

  /** A child node */
  public NodeListOptional nodeListOptional;

  /** A child node */
  public NodeToken nodeToken1;

  /** The serial version uid */
  private static final long serialVersionUID = 144L;

  /**
   * Constructs the node with all its children nodes.
   *
   * @param n0 first child node
   * @param n1 next child node
   * @param n2 next child node
   * @param n3 next child node
   * @param n4 next child node
   */
  public MultistateSpecies_SingleStateDefinition(final MultistateSpecies_SiteName n0, final NodeToken n1, final MultistateSpecies_SiteSingleElement n2, final NodeListOptional n3, final NodeToken n4) {
    multistateSpecies_SiteName = n0;
    nodeToken = n1;
    multistateSpecies_SiteSingleElement = n2;
    nodeListOptional = n3;
    nodeToken1 = n4;
  }

  /**
   * Constructs the node with only its non NodeToken child node(s).
   *
   * @param n0 first child node
   * @param n1 next child node
   * @param n2 next child node
   */
  public MultistateSpecies_SingleStateDefinition(final MultistateSpecies_SiteName n0, final MultistateSpecies_SiteSingleElement n1, final NodeListOptional n2) {
    multistateSpecies_SiteName = n0;
    nodeToken = new NodeToken("{");
    multistateSpecies_SiteSingleElement = n1;
    nodeListOptional = n2;
    nodeToken1 = new NodeToken("}");
  }

  /**
   * Accepts the IRetArguVisitor visitor.
   *
   * @param <R> the user return type
   * @param <A> the user argument type
   * @param vis the visitor
   * @param argu a user chosen argument
   * @return a user chosen return information
   */
  public <R, A> R accept(final IRetArguVisitor<R, A> vis, final A argu) {
    return vis.visit(this, argu);
  }

  /**
   * Accepts the IRetVisitor visitor.
   *
   * @param <R> the user return type
   * @param vis the visitor
   * @return a user chosen return information
   */
  public <R> R accept(final IRetVisitor<R> vis) {
    return vis.visit(this);
  }

  /**
   * Accepts the IVoidArguVisitor visitor.
   *
   * @param <A> the user argument type
   * @param vis the visitor
   * @param argu a user chosen argument
   */
  public <A> void accept(final IVoidArguVisitor<A> vis, final A argu) {
    vis.visit(this, argu);
  }

  /**
   * Accepts the IVoidVisitor visitor.
   *
   * @param vis the visitor
   */
  public void accept(final IVoidVisitor vis) {
    vis.visit(this);
  }

}
