/* Generated by JTB 1.4.4 */
package parsers.mathExpression.visitor;

import parsers.mathExpression.syntaxtree.*;
import java.util.*;

/**
 * Provides default methods which visit each node in the tree in depth-first order.<br>
 * In your "Void" visitors extend this class and override part or all of these methods.
 *
 */
public class DepthFirstVoidVisitor implements IVoidVisitor {


  /*
   * Base nodes classes visit methods (to be overridden if necessary)
   */

  /**
   * Visits a {@link NodeChoice} node.
   *
   * @param n the node to visit
   */
  public void visit(final NodeChoice n) {
    n.choice.accept(this);
    return;
  }

  /**
   * Visits a {@link NodeList} node.
   *
   * @param n the node to visit
   */
  public void visit(final NodeList n) {
    for (final Iterator<INode> e = n.elements(); e.hasNext();) {
      e.next().accept(this);
    }
    return;
  }

  /**
   * Visits a {@link NodeListOptional} node.
   *
   * @param n the node to visit
   */
  public void visit(final NodeListOptional n) {
    if (n.present()) {
      for (final Iterator<INode> e = n.elements(); e.hasNext();) {
        e.next().accept(this);
        }
      return;
    } else
      return;
  }

  /**
   * Visits a {@link NodeOptional} node.
   *
   * @param n the node to visit
   */
  public void visit(final NodeOptional n) {
    if (n.present()) {
      n.node.accept(this);
      return;
    } else
    return;
  }

  /**
   * Visits a {@link NodeSequence} node.
   *
   * @param n the node to visit
   */
  public void visit(final NodeSequence n) {
    for (final Iterator<INode> e = n.elements(); e.hasNext();) {
      e.next().accept(this);
    }
    return;
  }

  /**
   * Visits a {@link NodeToken} node.
   *
   * @param n the node to visit
   */
  public void visit(final NodeToken n) {
    @SuppressWarnings("unused")
    final String tkIm = n.tokenImage;
    return;
  }

  /*
   * User grammar generated visit methods (to be overridden if necessary)
   */

  /**
   * Visits a {@link CompleteExpression} node, whose children are the following :
   * <p>
   * expression -> Expression()<br>
   * nodeToken -> < EOF ><br>
   *
   * @param n the node to visit
   */
  public void visit(final CompleteExpression n) {
    // expression -> Expression()
    n.expression.accept(this);
    // nodeToken -> < EOF >
    n.nodeToken.accept(this);
  }

  /**
   * Visits a {@link CompleteListOfExpression} node, whose children are the following :
   * <p>
   * expression -> Expression()<br>
   * nodeListOptional -> ( #0 < COMMA > #1 Expression() )*<br>
   * nodeToken -> < EOF ><br>
   *
   * @param n the node to visit
   */
  public void visit(final CompleteListOfExpression n) {
    // expression -> Expression()
    n.expression.accept(this);
    // nodeListOptional -> ( #0 < COMMA > #1 Expression() )*
    n.nodeListOptional.accept(this);
    // nodeToken -> < EOF >
    n.nodeToken.accept(this);
  }

  /**
   * Visits a {@link SingleFunctionCall} node, whose children are the following :
   * <p>
   * name -> Name()<br>
   * nodeToken -> < LPAREN ><br>
   * nodeOptional -> ( ArgumentList() )?<br>
   * nodeToken1 -> < RPAREN ><br>
   * nodeToken2 -> < EOF ><br>
   *
   * @param n the node to visit
   */
  public void visit(final SingleFunctionCall n) {
    // name -> Name()
    n.name.accept(this);
    // nodeToken -> < LPAREN >
    n.nodeToken.accept(this);
    // nodeOptional -> ( ArgumentList() )?
    n.nodeOptional.accept(this);
    // nodeToken1 -> < RPAREN >
    n.nodeToken1.accept(this);
    // nodeToken2 -> < EOF >
    n.nodeToken2.accept(this);
  }

  /**
   * Visits a {@link CompleteFunctionDeclaration} node, whose children are the following :
   * <p>
   * functionDeclarator -> FunctionDeclarator()<br>
   * nodeToken -> < EOF ><br>
   *
   * @param n the node to visit
   */
  public void visit(final CompleteFunctionDeclaration n) {
    // functionDeclarator -> FunctionDeclarator()
    n.functionDeclarator.accept(this);
    // nodeToken -> < EOF >
    n.nodeToken.accept(this);
  }

  /**
   * Visits a {@link FunctionDeclarator} node, whose children are the following :
   * <p>
   * nodeToken -> < IDENTIFIER ><br>
   * nodeOptional -> ( FormalParameters() )?<br>
   *
   * @param n the node to visit
   */
  public void visit(final FunctionDeclarator n) {
    // nodeToken -> < IDENTIFIER >
    n.nodeToken.accept(this);
    // nodeOptional -> ( FormalParameters() )?
    n.nodeOptional.accept(this);
  }

  /**
   * Visits a {@link FormalParameters} node, whose children are the following :
   * <p>
   * nodeToken -> "("<br>
   * nodeOptional -> [ #0 FormalParameter()<br>
   * ............ .. . #1 ( $0 "," $1 FormalParameter() )* ]<br>
   * nodeToken1 -> ")"<br>
   *
   * @param n the node to visit
   */
  public void visit(final FormalParameters n) {
    // nodeToken -> "("
    n.nodeToken.accept(this);
    // nodeOptional -> [ #0 FormalParameter()
    // ............ .. . #1 ( $0 "," $1 FormalParameter() )* ]
    n.nodeOptional.accept(this);
    // nodeToken1 -> ")"
    n.nodeToken1.accept(this);
  }

  /**
   * Visits a {@link FormalParameter} node, whose children are the following :
   * <p>
   * primitiveType -> PrimitiveType()<br>
   * variableDeclaratorId -> VariableDeclaratorId()<br>
   *
   * @param n the node to visit
   */
  public void visit(final FormalParameter n) {
    // primitiveType -> PrimitiveType()
    n.primitiveType.accept(this);
    // variableDeclaratorId -> VariableDeclaratorId()
    n.variableDeclaratorId.accept(this);
  }

  /**
   * Visits a {@link PrimitiveType} node, whose children are the following :
   * <p>
   * nodeChoice -> . %0 < TYPE_PAR ><br>
   * .......... .. | %1 < TYPE_VAR ><br>
   * .......... .. | %2 < TYPE_SUB ><br>
   * .......... .. | %3 < TYPE_PROD ><br>
   * .......... .. | %4 < TYPE_MOD ><br>
   * .......... .. | %5 < TYPE_SITE ><br>
   * .......... .. | %6 < TYPE_VOL ><br>
   * .......... .. | %7 < TYPE_TIME ><br>
   *
   * @param n the node to visit
   */
  public void visit(final PrimitiveType n) {
    // nodeChoice -> . %0 < TYPE_PAR >
    // .......... .. | %1 < TYPE_VAR >
    // .......... .. | %2 < TYPE_SUB >
    // .......... .. | %3 < TYPE_PROD >
    // .......... .. | %4 < TYPE_MOD >
    // .......... .. | %5 < TYPE_SITE >
    // .......... .. | %6 < TYPE_VOL >
    // .......... .. | %7 < TYPE_TIME >
    n.nodeChoice.accept(this);
  }

  /**
   * Visits a {@link VariableDeclaratorId} node, whose children are the following :
   * <p>
   * nodeToken -> < IDENTIFIER ><br>
   *
   * @param n the node to visit
   */
  public void visit(final VariableDeclaratorId n) {
    // nodeToken -> < IDENTIFIER >
    n.nodeToken.accept(this);
  }

  /**
   * Visits a {@link IfExpression} node, whose children are the following :
   * <p>
   * nodeToken -> < IF ><br>
   * nodeToken1 -> < LPAREN ><br>
   * expression -> Expression()<br>
   * nodeToken2 -> < COMMA ><br>
   * expression1 -> Expression()<br>
   * nodeOptional -> ( #0 < COMMA > #1 Expression() )?<br>
   * nodeToken3 -> < RPAREN ><br>
   *
   * @param n the node to visit
   */
  public void visit(final IfExpression n) {
    // nodeToken -> < IF >
    n.nodeToken.accept(this);
    // nodeToken1 -> < LPAREN >
    n.nodeToken1.accept(this);
    // expression -> Expression()
    n.expression.accept(this);
    // nodeToken2 -> < COMMA >
    n.nodeToken2.accept(this);
    // expression1 -> Expression()
    n.expression1.accept(this);
    // nodeOptional -> ( #0 < COMMA > #1 Expression() )?
    n.nodeOptional.accept(this);
    // nodeToken3 -> < RPAREN >
    n.nodeToken3.accept(this);
  }

  /**
   * Visits a {@link Expression} node, whose children are the following :
   * <p>
   * additiveExpression -> AdditiveExpression()<br>
   * nodeOptional -> ( #0 RelationalOperator() #1 Expression()<br>
   * ............ .. . #2 ( $0 LogicalOperator() $1 Expression() )* )?<br>
   *
   * @param n the node to visit
   */
  public void visit(final Expression n) {
    // additiveExpression -> AdditiveExpression()
    n.additiveExpression.accept(this);
    // nodeOptional -> ( #0 RelationalOperator() #1 Expression()
    // ............ .. . #2 ( $0 LogicalOperator() $1 Expression() )* )?
    n.nodeOptional.accept(this);
  }

  /**
   * Visits a {@link RelationalOperator} node, whose children are the following :
   * <p>
   * nodeChoice -> . %0 ( &0 < ASSIGN ><br>
   * .......... .. . .. | &1 < EQ > )<br>
   * .......... .. | %1 < LT ><br>
   * .......... .. | %2 < GT ><br>
   * .......... .. | %3 < GEQ ><br>
   * .......... .. | %4 < LEQ ><br>
   *
   * @param n the node to visit
   */
  public void visit(final RelationalOperator n) {
    // nodeChoice -> . %0 ( &0 < ASSIGN >
    // .......... .. . .. | &1 < EQ > )
    // .......... .. | %1 < LT >
    // .......... .. | %2 < GT >
    // .......... .. | %3 < GEQ >
    // .......... .. | %4 < LEQ >
    n.nodeChoice.accept(this);
  }

  /**
   * Visits a {@link LogicalOperator} node, whose children are the following :
   * <p>
   * nodeChoice -> . %0 < AND ><br>
   * .......... .. | %1 < OR ><br>
   * .......... .. | %2 < XOR ><br>
   *
   * @param n the node to visit
   */
  public void visit(final LogicalOperator n) {
    // nodeChoice -> . %0 < AND >
    // .......... .. | %1 < OR >
    // .......... .. | %2 < XOR >
    n.nodeChoice.accept(this);
  }

  /**
   * Visits a {@link AdditiveExpression} node, whose children are the following :
   * <p>
   * multiplicativeExpression -> MultiplicativeExpression()<br>
   * nodeListOptional -> ( #0 ( %0 < PLUS ><br>
   * ................ .. . .. | %1 < MINUS > ) #1 MultiplicativeExpression() )*<br>
   *
   * @param n the node to visit
   */
  public void visit(final AdditiveExpression n) {
    // multiplicativeExpression -> MultiplicativeExpression()
    n.multiplicativeExpression.accept(this);
    // nodeListOptional -> ( #0 ( %0 < PLUS >
    // ................ .. . .. | %1 < MINUS > ) #1 MultiplicativeExpression() )*
    n.nodeListOptional.accept(this);
  }

  /**
   * Visits a {@link MultiplicativeExpression} node, whose children are the following :
   * <p>
   * powerExpression -> PowerExpression()<br>
   * nodeListOptional -> ( #0 ( %0 < TIMES ><br>
   * ................ .. . .. | %1 < DIV > ) #1 PowerExpression() )*<br>
   *
   * @param n the node to visit
   */
  public void visit(final MultiplicativeExpression n) {
    // powerExpression -> PowerExpression()
    n.powerExpression.accept(this);
    // nodeListOptional -> ( #0 ( %0 < TIMES >
    // ................ .. . .. | %1 < DIV > ) #1 PowerExpression() )*
    n.nodeListOptional.accept(this);
  }

  /**
   * Visits a {@link PowerExpression} node, whose children are the following :
   * <p>
   * unaryExpression -> UnaryExpression()<br>
   * nodeListOptional -> ( #0 ( < CARET > ) #1 UnaryExpression() )*<br>
   *
   * @param n the node to visit
   */
  public void visit(final PowerExpression n) {
    // unaryExpression -> UnaryExpression()
    n.unaryExpression.accept(this);
    // nodeListOptional -> ( #0 ( < CARET > ) #1 UnaryExpression() )*
    n.nodeListOptional.accept(this);
  }

  /**
   * Visits a {@link UnaryExpression} node, whose children are the following :
   * <p>
   * nodeChoice -> . %0 #0 ( &0 < PLUS ><br>
   * .......... .. . .. .. | &1 < MINUS > ) #1 UnaryExpression()<br>
   * .......... .. | %1 UnaryExpressionNotPlusMinus()<br>
   *
   * @param n the node to visit
   */
  public void visit(final UnaryExpression n) {
    // nodeChoice -> . %0 #0 ( &0 < PLUS >
    // .......... .. . .. .. | &1 < MINUS > ) #1 UnaryExpression()
    // .......... .. | %1 UnaryExpressionNotPlusMinus()
    n.nodeChoice.accept(this);
  }

  /**
   * Visits a {@link UnaryExpressionNotPlusMinus} node, whose children are the following :
   * <p>
   * nodeChoice -> . %0 #0 < BANG > #1 UnaryExpression()<br>
   * .......... .. | %1 PrimaryExpression()<br>
   *
   * @param n the node to visit
   */
  public void visit(final UnaryExpressionNotPlusMinus n) {
    // nodeChoice -> . %0 #0 < BANG > #1 UnaryExpression()
    // .......... .. | %1 PrimaryExpression()
    n.nodeChoice.accept(this);
  }

  /**
   * Visits a {@link PrimaryExpression} node, whose children are the following :
   * <p>
   * primaryPrefix -> PrimaryPrefix()<br>
   *
   * @param n the node to visit
   */
  public void visit(final PrimaryExpression n) {
    // primaryPrefix -> PrimaryPrefix()
    n.primaryPrefix.accept(this);
  }

  /**
   * Visits a {@link PrimaryPrefix} node, whose children are the following :
   * <p>
   * nodeChoice -> . %0 Literal()<br>
   * .......... .. | %1 #0 < LPAREN > #1 Expression() #2 < RPAREN ><br>
   * .......... .. | %2 SpeciesReferenceOrFunctionCall()<br>
   * .......... .. | %3 MultistateSum()<br>
   * .......... .. | %4 IfExpression()<br>
   * .......... .. | %5 < CONST_MODEL_TIME ><br>
   * .......... .. | %6 < CONST_AVOGADRO ><br>
   * .......... .. | %7 < CONST_QUANTITY_CONV_FACTOR ><br>
   * .......... .. | %8 < CONST_MODEL_TIME_INITIAL ><br>
   *
   * @param n the node to visit
   */
  public void visit(final PrimaryPrefix n) {
    // nodeChoice -> . %0 Literal()
    // .......... .. | %1 #0 < LPAREN > #1 Expression() #2 < RPAREN >
    // .......... .. | %2 SpeciesReferenceOrFunctionCall()
    // .......... .. | %3 MultistateSum()
    // .......... .. | %4 IfExpression()
    // .......... .. | %5 < CONST_MODEL_TIME >
    // .......... .. | %6 < CONST_AVOGADRO >
    // .......... .. | %7 < CONST_QUANTITY_CONV_FACTOR >
    // .......... .. | %8 < CONST_MODEL_TIME_INITIAL >
    n.nodeChoice.accept(this);
  }

  /**
   * Visits a {@link MultistateSum} node, whose children are the following :
   * <p>
   * nodeToken -> < SUM ><br>
   * nodeToken1 -> < LPAREN ><br>
   * argumentList_MultistateSum -> ArgumentList_MultistateSum()<br>
   * nodeToken2 -> < RPAREN ><br>
   *
   * @param n the node to visit
   */
  public void visit(final MultistateSum n) {
    // nodeToken -> < SUM >
    n.nodeToken.accept(this);
    // nodeToken1 -> < LPAREN >
    n.nodeToken1.accept(this);
    // argumentList_MultistateSum -> ArgumentList_MultistateSum()
    n.argumentList_MultistateSum.accept(this);
    // nodeToken2 -> < RPAREN >
    n.nodeToken2.accept(this);
  }

  /**
   * Visits a {@link Name} node, whose children are the following :
   * <p>
   * nodeChoice -> . %00 < IDENTIFIER ><br>
   * .......... .. | %01 PrimitiveType()<br>
   * .......... .. | %02 < PI ><br>
   * .......... .. | %03 < TIME ><br>
   * .......... .. | %04 < FLOOR ><br>
   * .......... .. | %05 < DELAY ><br>
   * .......... .. | %06 < CEIL ><br>
   * .......... .. | %07 < TAN ><br>
   * .......... .. | %08 < TANH ><br>
   * .......... .. | %09 < COSH ><br>
   * .......... .. | %10 < LOG10 ><br>
   * .......... .. | %11 < ABS ><br>
   * .......... .. | %12 < COS ><br>
   * .......... .. | %13 < SIN ><br>
   * .......... .. | %14 < LOG ><br>
   * .......... .. | %15 < EXP ><br>
   * .......... .. | %16 < NAN ><br>
   *
   * @param n the node to visit
   */
  public void visit(final Name n) {
    // nodeChoice -> . %00 < IDENTIFIER >
    // .......... .. | %01 PrimitiveType()
    // .......... .. | %02 < PI >
    // .......... .. | %03 < TIME >
    // .......... .. | %04 < FLOOR >
    // .......... .. | %05 < DELAY >
    // .......... .. | %06 < CEIL >
    // .......... .. | %07 < TAN >
    // .......... .. | %08 < TANH >
    // .......... .. | %09 < COSH >
    // .......... .. | %10 < LOG10 >
    // .......... .. | %11 < ABS >
    // .......... .. | %12 < COS >
    // .......... .. | %13 < SIN >
    // .......... .. | %14 < LOG >
    // .......... .. | %15 < EXP >
    // .......... .. | %16 < NAN >
    n.nodeChoice.accept(this);
  }

  /**
   * Visits a {@link SpeciesReferenceOrFunctionCall_prefix} node, whose children are the following :
   * <p>
   * name -> Name()<br>
   * nodeOptional -> [ #0 < LPAREN ><br>
   * ............ .. . #1 [ ArgumentList() ] #2 < RPAREN > ]<br>
   *
   * @param n the node to visit
   */
  public void visit(final SpeciesReferenceOrFunctionCall_prefix n) {
    // name -> Name()
    n.name.accept(this);
    // nodeOptional -> [ #0 < LPAREN >
    // ............ .. . #1 [ ArgumentList() ] #2 < RPAREN > ]
    n.nodeOptional.accept(this);
  }

  /**
   * Visits a {@link SpeciesReferenceOrFunctionCall} node, whose children are the following :
   * <p>
   * speciesReferenceOrFunctionCall_prefix -> SpeciesReferenceOrFunctionCall_prefix()<br>
   * nodeListOptional -> ( ( PossibleExtensions() ) )*<br>
   *
   * @param n the node to visit
   */
  public void visit(final SpeciesReferenceOrFunctionCall n) {
    // speciesReferenceOrFunctionCall_prefix -> SpeciesReferenceOrFunctionCall_prefix()
    n.speciesReferenceOrFunctionCall_prefix.accept(this);
    // nodeListOptional -> ( ( PossibleExtensions() ) )*
    n.nodeListOptional.accept(this);
  }

  /**
   * Visits a {@link PossibleExtensions} node, whose children are the following :
   * <p>
   * nodeChoice -> ( %00 < EXTENSION_CONC ><br>
   * .......... .. | %01 < EXTENSION_COMPARTMENT ><br>
   * .......... .. | %02 < EXTENSION_PARTICLE ><br>
   * .......... .. | %03 < EXTENSION_TRANS ><br>
   * .......... .. | %04 < EXTENSION_INIT ><br>
   * .......... .. | %05 < EXTENSION_RATE ><br>
   * .......... .. | %06 < EXTENSION_SPECIES ><br>
   * .......... .. | %07 < EXTENSION_GLOBALQ ><br>
   * .......... .. | %08 < EXTENSION_FUNCTION ><br>
   * .......... .. | %09 < EXTENSION_REACTION ><br>
   * .......... .. | %10 < EXTENSION_FLUX ><br>
   * .......... .. | %11 < MY_SPECIAL_EXTENSION > )<br>
   * nodeListOptional -> ( PossibleExtensions() )*<br>
   *
   * @param n the node to visit
   */
  public void visit(final PossibleExtensions n) {
    // nodeChoice -> ( %00 < EXTENSION_CONC >
    // .......... .. | %01 < EXTENSION_COMPARTMENT >
    // .......... .. | %02 < EXTENSION_PARTICLE >
    // .......... .. | %03 < EXTENSION_TRANS >
    // .......... .. | %04 < EXTENSION_INIT >
    // .......... .. | %05 < EXTENSION_RATE >
    // .......... .. | %06 < EXTENSION_SPECIES >
    // .......... .. | %07 < EXTENSION_GLOBALQ >
    // .......... .. | %08 < EXTENSION_FUNCTION >
    // .......... .. | %09 < EXTENSION_REACTION >
    // .......... .. | %10 < EXTENSION_FLUX >
    // .......... .. | %11 < MY_SPECIAL_EXTENSION > )
    n.nodeChoice.accept(this);
    // nodeListOptional -> ( PossibleExtensions() )*
    n.nodeListOptional.accept(this);
  }

  /**
   * Visits a {@link Literal} node, whose children are the following :
   * <p>
   * nodeChoice -> . %0 < INTEGER_LITERAL ><br>
   * .......... .. | %1 < FLOATING_POINT_LITERAL ><br>
   * .......... .. | %2 BooleanLiteral()<br>
   *
   * @param n the node to visit
   */
  public void visit(final Literal n) {
    // nodeChoice -> . %0 < INTEGER_LITERAL >
    // .......... .. | %1 < FLOATING_POINT_LITERAL >
    // .......... .. | %2 BooleanLiteral()
    n.nodeChoice.accept(this);
  }

  /**
   * Visits a {@link BooleanLiteral} node, whose children are the following :
   * <p>
   * nodeChoice -> . %0 < TRUE ><br>
   * .......... .. | %1 < FALSE ><br>
   *
   * @param n the node to visit
   */
  public void visit(final BooleanLiteral n) {
    // nodeChoice -> . %0 < TRUE >
    // .......... .. | %1 < FALSE >
    n.nodeChoice.accept(this);
  }

  /**
   * Visits a {@link ArgumentList} node, whose children are the following :
   * <p>
   * nodeChoice -> . %0 MultistateSites_list()<br>
   * .......... .. | %1 #0 AdditiveExpression()<br>
   * .......... .. . .. #1 ( $0 < COMMA > $1 AdditiveExpression() )*<br>
   *
   * @param n the node to visit
   */
  public void visit(final ArgumentList n) {
    // nodeChoice -> . %0 MultistateSites_list()
    // .......... .. | %1 #0 AdditiveExpression()
    // .......... .. . .. #1 ( $0 < COMMA > $1 AdditiveExpression() )*
    n.nodeChoice.accept(this);
  }

  /**
   * Visits a {@link ArgumentList_MultistateSum} node, whose children are the following :
   * <p>
   * name -> Name()<br>
   * nodeOptional -> [ ArgumentList_MultistateSum_Selectors() ]<br>
   *
   * @param n the node to visit
   */
  public void visit(final ArgumentList_MultistateSum n) {
    // name -> Name()
    n.name.accept(this);
    // nodeOptional -> [ ArgumentList_MultistateSum_Selectors() ]
    n.nodeOptional.accept(this);
  }

  /**
   * Visits a {@link ArgumentList_MultistateSum_Selectors} node, whose children are the following :
   * <p>
   * nodeToken -> < SEMICOLON ><br>
   * selector -> Selector()<br>
   * nodeListOptional -> ( #0 < SEMICOLON > #1 Selector() )*<br>
   *
   * @param n the node to visit
   */
  public void visit(final ArgumentList_MultistateSum_Selectors n) {
    // nodeToken -> < SEMICOLON >
    n.nodeToken.accept(this);
    // selector -> Selector()
    n.selector.accept(this);
    // nodeListOptional -> ( #0 < SEMICOLON > #1 Selector() )*
    n.nodeListOptional.accept(this);
  }

  /**
   * Visits a {@link Selector} node, whose children are the following :
   * <p>
   * name -> Name()<br>
   * nodeOptional -> [ %0 SiteSelector_postFix()<br>
   * ............ .. | %1 CoeffFunction_postFix() ]<br>
   *
   * @param n the node to visit
   */
  public void visit(final Selector n) {
    // name -> Name()
    n.name.accept(this);
    // nodeOptional -> [ %0 SiteSelector_postFix()
    // ............ .. | %1 CoeffFunction_postFix() ]
    n.nodeOptional.accept(this);
  }

  /**
   * Visits a {@link SiteSelector_postFix} node, whose children are the following :
   * <p>
   * nodeToken -> < LBRACE ><br>
   * nodeChoice -> ( %0 Name()<br>
   * .......... .. | %1 Literal() )<br>
   * nodeOptional -> ( %0 ( #0 < COMMA ><br>
   * ............ .. . #1 ( &0 Name()<br>
   * ............ .. . .. | &1 Literal() ) )+<br>
   * ............ .. | %1 ( #0 < COLON ><br>
   * ............ .. . .. . #1 ( &0 Name()<br>
   * ............ .. . .. . .. | &1 Literal() ) ) )?<br>
   * nodeToken1 -> < RBRACE ><br>
   *
   * @param n the node to visit
   */
  public void visit(final SiteSelector_postFix n) {
    // nodeToken -> < LBRACE >
    n.nodeToken.accept(this);
    // nodeChoice -> ( %0 Name()
    // .......... .. | %1 Literal() )
    n.nodeChoice.accept(this);
    // nodeOptional -> ( %0 ( #0 < COMMA >
    // ............ .. . #1 ( &0 Name()
    // ............ .. . .. | &1 Literal() ) )+
    // ............ .. | %1 ( #0 < COLON >
    // ............ .. . .. . #1 ( &0 Name()
    // ............ .. . .. . .. | &1 Literal() ) ) )?
    n.nodeOptional.accept(this);
    // nodeToken1 -> < RBRACE >
    n.nodeToken1.accept(this);
  }

  /**
   * Visits a {@link CoeffFunction_postFix} node, whose children are the following :
   * <p>
   * nodeToken -> < LPAREN ><br>
   * nodeOptional -> [ ArgumentList() ]<br>
   * nodeToken1 -> < RPAREN ><br>
   *
   * @param n the node to visit
   */
  public void visit(final CoeffFunction_postFix n) {
    // nodeToken -> < LPAREN >
    n.nodeToken.accept(this);
    // nodeOptional -> [ ArgumentList() ]
    n.nodeOptional.accept(this);
    // nodeToken1 -> < RPAREN >
    n.nodeToken1.accept(this);
  }

  /**
   * Visits a {@link MultistateSite} node, whose children are the following :
   * <p>
   * name -> Name()<br>
   * nodeToken -> < LBRACE ><br>
   * nodeChoice -> ( %0 Name()<br>
   * .......... .. | %1 Literal() )<br>
   * nodeToken1 -> < RBRACE ><br>
   *
   * @param n the node to visit
   */
  public void visit(final MultistateSite n) {
    // name -> Name()
    n.name.accept(this);
    // nodeToken -> < LBRACE >
    n.nodeToken.accept(this);
    // nodeChoice -> ( %0 Name()
    // .......... .. | %1 Literal() )
    n.nodeChoice.accept(this);
    // nodeToken1 -> < RBRACE >
    n.nodeToken1.accept(this);
  }

  /**
   * Visits a {@link MultistateSites_list} node, whose children are the following :
   * <p>
   * multistateSite -> MultistateSite()<br>
   * nodeListOptional -> ( #0 < SEMICOLON > #1 MultistateSite() )*<br>
   *
   * @param n the node to visit
   */
  public void visit(final MultistateSites_list n) {
    // multistateSite -> MultistateSite()
    n.multistateSite.accept(this);
    // nodeListOptional -> ( #0 < SEMICOLON > #1 MultistateSite() )*
    n.nodeListOptional.accept(this);
  }

}
