/* Generated by JTB 1.4.4 */
package msmb.parsers.mathExpression.syntaxtree;

import msmb.parsers.mathExpression.visitor.*;

/**
 * JTB node class for the production PossibleExtensions:<br>
 * Corresponding grammar :<br>
 * nodeChoice -> ( %00 < EXTENSION_CONC ><br>
 * .......... .. | %01 < EXTENSION_COMPARTMENT ><br>
 * .......... .. | %02 < EXTENSION_PARTICLE ><br>
 * .......... .. | %03 < EXTENSION_TRANS ><br>
 * .......... .. | %04 < EXTENSION_INIT ><br>
 * .......... .. | %05 < EXTENSION_RATE ><br>
 * .......... .. | %06 < EXTENSION_SPECIES ><br>
 * .......... .. | %07 < EXTENSION_GLOBALQ ><br>
 * .......... .. | %08 < EXTENSION_FUNCTION ><br>
 * .......... .. | %09 < EXTENSION_REACTION ><br>
 * .......... .. | %10 < EXTENSION_FLUX ><br>
 * .......... .. | %11 < MY_SPECIAL_EXTENSION > )<br>
 * nodeListOptional -> ( PossibleExtensions() )*<br>
 */
public class PossibleExtensions implements INode {

  /** A child node */
  public NodeChoice nodeChoice;

  /** A child node */
  public NodeListOptional nodeListOptional;

  /** The serial version uid */
  private static final long serialVersionUID = 144L;

  /**
   * Constructs the node with all its children nodes.
   *
   * @param n0 first child node
   * @param n1 next child node
   */
  public PossibleExtensions(final NodeChoice n0, final NodeListOptional n1) {
    nodeChoice = n0;
    nodeListOptional = n1;
  }

  /**
   * Accepts the IRetArguVisitor visitor.
   *
   * @param <R> the user return type
   * @param <A> the user argument type
   * @param vis the visitor
   * @param argu a user chosen argument
   * @return a user chosen return information
   */
  public <R, A> R accept(final IRetArguVisitor<R, A> vis, final A argu) {
    return vis.visit(this, argu);
  }

  /**
   * Accepts the IRetVisitor visitor.
   *
   * @param <R> the user return type
   * @param vis the visitor
   * @return a user chosen return information
   */
  public <R> R accept(final IRetVisitor<R> vis) {
    return vis.visit(this);
  }

  /**
   * Accepts the IVoidArguVisitor visitor.
   *
   * @param <A> the user argument type
   * @param vis the visitor
   * @param argu a user chosen argument
   */
  public <A> void accept(final IVoidArguVisitor<A> vis, final A argu) {
    vis.visit(this, argu);
  }

  /**
   * Accepts the IVoidVisitor visitor.
   *
   * @param vis the visitor
   */
  public void accept(final IVoidVisitor vis) {
    vis.visit(this);
  }

}
