/* Generated By:JavaCC: Do not edit this line. MR_Expression_Parser.java */
package parsers.mathExpression;

import parsers.mathExpression.syntaxtree.*;
import parsers.mathExpression.visitor.*;
import java.io.*;
import parsers.mathExpression.syntaxtree.*;


public class MR_Expression_Parser implements MR_Expression_ParserConstants {

  public static void main(String args[]) {
    try {
      String expression = new String("1*floor(Time/tau)");
      InputStream is = new ByteArrayInputStream(expression.getBytes("UTF-8"));
      MR_Expression_Parser react = new MR_Expression_Parser(is);
      CompleteExpression start = react.CompleteExpression();
      DepthFirstVoidVisitor v = new MyVisitor();
      start.accept(v);
      System.out.println("...................................");
      String expression2 = new String("(asdf < sdf && (a < 3 && a > 4)) > 1");
      InputStream is2 = new ByteArrayInputStream(expression2.getBytes("UTF-8"));
      MR_Expression_Parser react2 = new MR_Expression_Parser(is2);
      CompleteExpression start2 = react2.CompleteExpression();
      DepthFirstVoidVisitor v2 = new MyVisitor();
      start2.accept(v2);
      System.out.println("...................................");
      expression2 = new String("if(ara> 0 && pulse_flag==1,cAra,dAra*ara)");
      is2 = new ByteArrayInputStream(expression2.getBytes("UTF-8"));
      react2 = new MR_Expression_Parser(is2);
      start2 = react2.CompleteExpression();
      v2 = new MyVisitor();
      start2.accept(v2);
      System.out.println("...................................");
      expression2 = new String("asdf < sdf xor (a < 3 && a > 4)");
      is2 = new ByteArrayInputStream(expression2.getBytes("UTF-8"));
      react2 = new MR_Expression_Parser(is2);
      start2 = react2.CompleteExpression();
      v2 = new MyVisitor();
      start2.accept(v2);
      System.out.println("...................................");
      expression2 = new String("if(24 < 0 xor Time < 0,Time-24*ceil(Time/24),Time-24*floor(Time/24)) > 1");
      is2 = new ByteArrayInputStream(expression2.getBytes("UTF-8"));
      react2 = new MR_Expression_Parser(is2);
      start2 = react2.CompleteExpression();
      v2 = new MyVisitor();
      start2.accept(v2);
      System.out.println("...................................");
      expression2 = new String("if(X1 > 0,Ks^\u005c"No. of transit compartment (slow)\u005c"/6*exp(-Ks*X1)*X1^(\u005c"No. of transit compartment (slow)\u005c"-1),0)");
      is2 = new ByteArrayInputStream(expression2.getBytes("UTF-8"));
      react2 = new MR_Expression_Parser(is2);
      start2 = react2.CompleteExpression();
      v2 = new MyVisitor();
      start2.accept(v2);
      System.out.println("...................................");
      expression2 = new String("1/((exp(0.15*(-V-50))+1))");
      is2 = new ByteArrayInputStream(expression2.getBytes("UTF-8"));
      react2 = new MR_Expression_Parser(is2);
      start2 = react2.CompleteExpression();
      v2 = new MyVisitor();
      start2.accept(v2);
      System.out.println("...................................");
      expression2 = new String("\u005c"funaasdf \u005c"(GLQ v, GLQ t)");
      is2 = new ByteArrayInputStream(expression2.getBytes("UTF-8"));
      react2 = new MR_Expression_Parser(is2);
      CompleteFunctionDeclaration start3 = react2.CompleteFunctionDeclaration();
      v2 = new MyVisitor();
      start3.accept(v2);
      System.out.println("...................................");
      expression2 = new String("function(par1, par2, %ModTime%)");
      is2 = new ByteArrayInputStream(expression2.getBytes("UTF-8"));
      react2 = new MR_Expression_Parser(is2);
      start2 = react2.CompleteExpression();
      v2 = new MyVisitor();
      start2.accept(v2);
      System.out.println("...................................");
      expression2 = new String("k1*a^b");
      is2 = new ByteArrayInputStream(expression2.getBytes("UTF-8"));
      react2 = new MR_Expression_Parser(is2);
      start2 = react2.CompleteExpression();
      v2 = new MyVisitor();
      start2.accept(v2);
      System.out.println("...................................");
      expression2 = new String("k1 * a^b");
      is2 = new ByteArrayInputStream(expression2.getBytes("UTF-8"));
      react2 = new MR_Expression_Parser(is2);
      start2 = react2.CompleteExpression();
      v2 = new MyVisitor();
      start2.accept(v2);
      System.out.println("...................................");
      expression2 = new String("NaN");
      is2 = new ByteArrayInputStream(expression2.getBytes("UTF-8"));
      react2 = new MR_Expression_Parser(is2);
      start2 = react2.CompleteExpression();
      v2 = new MyVisitor();
      start2.accept(v2);
      System.out.println("...................................");
      expression2 = new String("SUM(Cdh1)");
      is2 = new ByteArrayInputStream(expression2.getBytes("UTF-8"));
      react2 = new MR_Expression_Parser(is2);
      start2 = react2.CompleteExpression();
      v2 = new MyVisitor();
      start2.accept(v2);
      System.out.println("...................................");
      expression2 = new String("SUM(Cdh1;p)");
      is2 = new ByteArrayInputStream(expression2.getBytes("UTF-8"));
      react2 = new MR_Expression_Parser(is2);
      start2 = react2.CompleteExpression();
      v2 = new MyVisitor();
      start2.accept(v2);
      System.out.println("...................................");
      expression2 = new String("SUM(Cdh1;p{2,3})");
      is2 = new ByteArrayInputStream(expression2.getBytes("UTF-8"));
      react2 = new MR_Expression_Parser(is2);
      start2 = react2.CompleteExpression();
      v2 = new MyVisitor();
      start2.accept(v2);
      System.out.println("...................................");
      expression2 = new String("SUM(Cdh1;p{2,3}; weight(p,k1))");
      is2 = new ByteArrayInputStream(expression2.getBytes("UTF-8"));
      react2 = new MR_Expression_Parser(is2);
      start2 = react2.CompleteExpression();
      v2 = new MyVisitor();
      start2.accept(v2);
      System.out.println("...................................");
      expression2 = new String("SUM(Cdh1;p{0:10};q)");
      is2 = new ByteArrayInputStream(expression2.getBytes("UTF-8"));
      react2 = new MR_Expression_Parser(is2);
      start2 = react2.CompleteExpression();
      v2 = new MyVisitor();
      start2.accept(v2);
      System.out.println("...................................");
      expression2 = new String("kmisfoldSUB*SUB*(ROS*cytosol)");
      is2 = new ByteArrayInputStream(expression2.getBytes("UTF-8"));
      react2 = new MR_Expression_Parser(is2);
      start2 = react2.CompleteExpression();
      v2 = new MyVisitor();
      start2.accept(v2);
      System.out.println("...................................");
      expression2 = new String("1e-006*k*GAP*MOD");
      is2 = new ByteArrayInputStream(expression2.getBytes("UTF-8"));
      react2 = new MR_Expression_Parser(is2);
      start2 = react2.CompleteExpression();
      v2 = new MyVisitor();
      start2.accept(v2);
      System.out.println("...................................");
    }
    catch (Exception ex) {
      ex.printStackTrace();
    }
  }

/*****************************************
 * THE MULTIREMI EXPRESSION GRAMMAR STARTS HERE *
 *****************************************/
  final public CompleteExpression CompleteExpression() throws ParseException {
  // --- JTB generated node declarations ---
  Expression n0 = null;
  NodeToken n1 = null;
  Token n2 = null;
    n0 = Expression();
    n2 = jj_consume_token(0);
    n2.beginColumn++;
    n2.endColumn++;
    { n1 = JTBToolkit.makeNodeToken(n2); }
    {if (true) return new CompleteExpression(n0, n1);}
    throw new Error("Missing return statement in function");
  }

  final public SingleFunctionCall SingleFunctionCall() throws ParseException {
  // --- JTB generated node declarations ---
  Name n0 = null;
  NodeToken n1 = null;
  Token n2 = null;
  NodeOptional n3 = new NodeOptional();
  ArgumentList n4 = null;
  NodeToken n5 = null;
  Token n6 = null;
  NodeToken n7 = null;
  Token n8 = null;
    n0 = Name();
    n2 = jj_consume_token(LPAREN);
    n1 = JTBToolkit.makeNodeToken(n2);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IF:
    case FALSE:
    case TRUE:
    case TIME:
    case TYPE_PAR:
    case TYPE_VAR:
    case TYPE_SUB:
    case TYPE_PROD:
    case TYPE_MOD:
    case TYPE_SITE:
    case TYPE_VOL:
    case TYPE_TIME:
    case SUM:
    case DELAY:
    case FLOOR:
    case CEIL:
    case COS:
    case SIN:
    case TAN:
    case TANH:
    case COSH:
    case EXP:
    case LOG:
    case LOG10:
    case ABS:
    case PI:
    case NAN:
    case CONST_AVOGADRO:
    case CONST_QUANTITY_CONV_FACTOR:
    case CONST_MODEL_TIME:
    case CONST_MODEL_TIME_INITIAL:
    case INTEGER_LITERAL:
    case FLOATING_POINT_LITERAL:
    case LPAREN:
    case PLUS:
    case MINUS:
    case BANG:
    case IDENTIFIER:
      n4 = ArgumentList();
      n3.addNode(n4);
      break;
    default:
      jj_la1[0] = jj_gen;
      ;
    }
    n6 = jj_consume_token(RPAREN);
    n5 = JTBToolkit.makeNodeToken(n6);
    n8 = jj_consume_token(0);
    n8.beginColumn++;
    n8.endColumn++;
    { n7 = JTBToolkit.makeNodeToken(n8); }
    {if (true) return new SingleFunctionCall(n0, n1, n3, n5, n7);}
    throw new Error("Missing return statement in function");
  }

  final public CompleteFunctionDeclaration CompleteFunctionDeclaration() throws ParseException {
  // --- JTB generated node declarations ---
  FunctionDeclarator n0 = null;
  NodeToken n1 = null;
  Token n2 = null;
    n0 = FunctionDeclarator();
    n2 = jj_consume_token(0);
    n2.beginColumn++;
    n2.endColumn++;
    { n1 = JTBToolkit.makeNodeToken(n2); }
    {if (true) return new CompleteFunctionDeclaration(n0, n1);}
    throw new Error("Missing return statement in function");
  }

  final public FunctionDeclarator FunctionDeclarator() throws ParseException {
  // --- JTB generated node declarations ---
  NodeToken n0 = null;
  Token n1 = null;
  NodeOptional n2 = new NodeOptional();
  FormalParameters n3 = null;
    n1 = jj_consume_token(IDENTIFIER);
    n0 = JTBToolkit.makeNodeToken(n1);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case LPAREN:
      n3 = FormalParameters();
      n2.addNode(n3);
      break;
    default:
      jj_la1[1] = jj_gen;
      ;
    }
    {if (true) return new FunctionDeclarator(n0, n2);}
    throw new Error("Missing return statement in function");
  }

  final public FormalParameters FormalParameters() throws ParseException {
  // --- JTB generated node declarations ---
  NodeToken n0 = null;
  Token n1 = null;
  NodeOptional n2 = new NodeOptional();
  NodeSequence n3 = null;
  FormalParameter n4 = null;
  NodeListOptional n5 = null;
  NodeSequence n6 = null;
  NodeToken n7 = null;
  Token n8 = null;
  FormalParameter n9 = null;
  NodeToken n10 = null;
  Token n11 = null;
    n1 = jj_consume_token(LPAREN);
    n0 = JTBToolkit.makeNodeToken(n1);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case TYPE_PAR:
    case TYPE_VAR:
    case TYPE_SUB:
    case TYPE_PROD:
    case TYPE_MOD:
    case TYPE_SITE:
    case TYPE_VOL:
    case TYPE_TIME:
      n5 = new NodeListOptional();
      n3 = new NodeSequence(2);
      n4 = FormalParameter();
      n3.addNode(n4);
      label_1:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case COMMA:
          ;
          break;
        default:
          jj_la1[2] = jj_gen;
          break label_1;
        }
        n6 = new NodeSequence(2);
        n8 = jj_consume_token(COMMA);
        n7 = JTBToolkit.makeNodeToken(n8);
        n6.addNode(n7);
        n9 = FormalParameter();
        n6.addNode(n9);
        n5.addNode(n6);
      }
      n5.nodes.trimToSize();
      n3.addNode(n5);
      n2.addNode(n3);
      break;
    default:
      jj_la1[3] = jj_gen;
      ;
    }
    n11 = jj_consume_token(RPAREN);
    n10 = JTBToolkit.makeNodeToken(n11);
    {if (true) return new FormalParameters(n0, n2, n10);}
    throw new Error("Missing return statement in function");
  }

  final public FormalParameter FormalParameter() throws ParseException {
  // --- JTB generated node declarations ---
  PrimitiveType n0 = null;
  VariableDeclaratorId n1 = null;
    n0 = PrimitiveType();
    n1 = VariableDeclaratorId();
    {if (true) return new FormalParameter(n0, n1);}
    throw new Error("Missing return statement in function");
  }

  final public PrimitiveType PrimitiveType() throws ParseException {
  // --- JTB generated node declarations ---
  NodeChoice n0 = null;
  NodeToken n1 = null;
  Token n2 = null;
  NodeToken n3 = null;
  Token n4 = null;
  NodeToken n5 = null;
  Token n6 = null;
  NodeToken n7 = null;
  Token n8 = null;
  NodeToken n9 = null;
  Token n10 = null;
  NodeToken n11 = null;
  Token n12 = null;
  NodeToken n13 = null;
  Token n14 = null;
  NodeToken n15 = null;
  Token n16 = null;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case TYPE_PAR:
      n2 = jj_consume_token(TYPE_PAR);
      n1 = JTBToolkit.makeNodeToken(n2);
      n0 = new NodeChoice(n1, 0, 8);
      break;
    case TYPE_VAR:
      n4 = jj_consume_token(TYPE_VAR);
      n3 = JTBToolkit.makeNodeToken(n4);
      n0 = new NodeChoice(n3, 1, 8);
      break;
    case TYPE_SUB:
      n6 = jj_consume_token(TYPE_SUB);
      n5 = JTBToolkit.makeNodeToken(n6);
      n0 = new NodeChoice(n5, 2, 8);
      break;
    case TYPE_PROD:
      n8 = jj_consume_token(TYPE_PROD);
      n7 = JTBToolkit.makeNodeToken(n8);
      n0 = new NodeChoice(n7, 3, 8);
      break;
    case TYPE_MOD:
      n10 = jj_consume_token(TYPE_MOD);
      n9 = JTBToolkit.makeNodeToken(n10);
      n0 = new NodeChoice(n9, 4, 8);
      break;
    case TYPE_SITE:
      n12 = jj_consume_token(TYPE_SITE);
      n11 = JTBToolkit.makeNodeToken(n12);
      n0 = new NodeChoice(n11, 5, 8);
      break;
    case TYPE_VOL:
      n14 = jj_consume_token(TYPE_VOL);
      n13 = JTBToolkit.makeNodeToken(n14);
      n0 = new NodeChoice(n13, 6, 8);
      break;
    case TYPE_TIME:
      n16 = jj_consume_token(TYPE_TIME);
      n15 = JTBToolkit.makeNodeToken(n16);
      n0 = new NodeChoice(n15, 7, 8);
      break;
    default:
      jj_la1[4] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    {if (true) return new PrimitiveType(n0);}
    throw new Error("Missing return statement in function");
  }

  final public VariableDeclaratorId VariableDeclaratorId() throws ParseException {
  // --- JTB generated node declarations ---
  NodeToken n0 = null;
  Token n1 = null;
    n1 = jj_consume_token(IDENTIFIER);
    n0 = JTBToolkit.makeNodeToken(n1);
    {if (true) return new VariableDeclaratorId(n0);}
    throw new Error("Missing return statement in function");
  }

  final public IfExpression IfExpression() throws ParseException {
  // --- JTB generated node declarations ---
  NodeToken n0 = null;
  Token n1 = null;
  NodeToken n2 = null;
  Token n3 = null;
  Expression n4 = null;
  NodeToken n5 = null;
  Token n6 = null;
  Expression n7 = null;
  NodeOptional n8 = new NodeOptional();
  NodeSequence n9 = null;
  NodeToken n10 = null;
  Token n11 = null;
  Expression n12 = null;
  NodeToken n13 = null;
  Token n14 = null;
    n1 = jj_consume_token(IF);
    n0 = JTBToolkit.makeNodeToken(n1);
    n3 = jj_consume_token(LPAREN);
    n2 = JTBToolkit.makeNodeToken(n3);
    n4 = Expression();
    n6 = jj_consume_token(COMMA);
    n5 = JTBToolkit.makeNodeToken(n6);
    n7 = Expression();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case COMMA:
      n9 = new NodeSequence(2);
      n11 = jj_consume_token(COMMA);
      n10 = JTBToolkit.makeNodeToken(n11);
      n9.addNode(n10);
      n12 = Expression();
      n9.addNode(n12);
      n8.addNode(n9);
      break;
    default:
      jj_la1[5] = jj_gen;
      ;
    }
    n14 = jj_consume_token(RPAREN);
    n13 = JTBToolkit.makeNodeToken(n14);
    {if (true) return new IfExpression(n0, n2, n4, n5, n7, n8, n13);}
    throw new Error("Missing return statement in function");
  }

  final public Expression Expression() throws ParseException {
  // --- JTB generated node declarations ---
  AdditiveExpression n0 = null;
  NodeOptional n1 = new NodeOptional();
  NodeSequence n2 = null;
  RelationalOperator n3 = null;
  Expression n4 = null;
  NodeListOptional n5 = null;
  NodeSequence n6 = null;
  LogicalOperator n7 = null;
  Expression n8 = null;
    n0 = AdditiveExpression();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case ASSIGN:
    case GT:
    case LT:
    case EQ:
    case LEQ:
    case GEQ:
      n5 = new NodeListOptional();
      n2 = new NodeSequence(3);
      n3 = RelationalOperator();
      n2.addNode(n3);
      n4 = Expression();
      n2.addNode(n4);
      label_2:
      while (true) {
        if (jj_2_1(2)) {
          ;
        } else {
          break label_2;
        }
        n6 = new NodeSequence(2);
        n7 = LogicalOperator();
        n6.addNode(n7);
        n8 = Expression();
        n6.addNode(n8);
        n5.addNode(n6);
      }
      n5.nodes.trimToSize();
      n2.addNode(n5);
      n1.addNode(n2);
      break;
    default:
      jj_la1[6] = jj_gen;
      ;
    }
    {if (true) return new Expression(n0, n1);}
    throw new Error("Missing return statement in function");
  }

  final public RelationalOperator RelationalOperator() throws ParseException {
  // --- JTB generated node declarations ---
  NodeChoice n0 = null;
  NodeChoice n1 = null;
  NodeToken n2 = null;
  Token n3 = null;
  NodeToken n4 = null;
  Token n5 = null;
  NodeToken n6 = null;
  Token n7 = null;
  NodeToken n8 = null;
  Token n9 = null;
  NodeToken n10 = null;
  Token n11 = null;
  NodeToken n12 = null;
  Token n13 = null;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case ASSIGN:
    case EQ:
      if (jj_2_2(2)) {
        n3 = jj_consume_token(ASSIGN);
          n2 = JTBToolkit.makeNodeToken(n3);
          n1 = new NodeChoice(n2, 0, 2);
      } else {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case EQ:
          n5 = jj_consume_token(EQ);
          n4 = JTBToolkit.makeNodeToken(n5);
          n1 = new NodeChoice(n4, 1, 2);
          break;
        default:
          jj_la1[7] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
      n0 = new NodeChoice(n1, 0, 5);
      break;
    case LT:
      n7 = jj_consume_token(LT);
      n6 = JTBToolkit.makeNodeToken(n7);
      n0 = new NodeChoice(n6, 1, 5);
      break;
    case GT:
      n9 = jj_consume_token(GT);
      n8 = JTBToolkit.makeNodeToken(n9);
      n0 = new NodeChoice(n8, 2, 5);
      break;
    case GEQ:
      n11 = jj_consume_token(GEQ);
      n10 = JTBToolkit.makeNodeToken(n11);
      n0 = new NodeChoice(n10, 3, 5);
      break;
    case LEQ:
      n13 = jj_consume_token(LEQ);
      n12 = JTBToolkit.makeNodeToken(n13);
      n0 = new NodeChoice(n12, 4, 5);
      break;
    default:
      jj_la1[8] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    {if (true) return new RelationalOperator(n0);}
    throw new Error("Missing return statement in function");
  }

  final public LogicalOperator LogicalOperator() throws ParseException {
  // --- JTB generated node declarations ---
  NodeChoice n0 = null;
  NodeToken n1 = null;
  Token n2 = null;
  NodeToken n3 = null;
  Token n4 = null;
  NodeToken n5 = null;
  Token n6 = null;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case AND:
      n2 = jj_consume_token(AND);
      n1 = JTBToolkit.makeNodeToken(n2);
      n0 = new NodeChoice(n1, 0, 3);
      break;
    case OR:
      n4 = jj_consume_token(OR);
      n3 = JTBToolkit.makeNodeToken(n4);
      n0 = new NodeChoice(n3, 1, 3);
      break;
    case XOR:
      n6 = jj_consume_token(XOR);
      n5 = JTBToolkit.makeNodeToken(n6);
      n0 = new NodeChoice(n5, 2, 3);
      break;
    default:
      jj_la1[9] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    {if (true) return new LogicalOperator(n0);}
    throw new Error("Missing return statement in function");
  }

  final public AdditiveExpression AdditiveExpression() throws ParseException {
  // --- JTB generated node declarations ---
  MultiplicativeExpression n0 = null;
  NodeListOptional n1 = new NodeListOptional();
  NodeSequence n2 = null;
  NodeChoice n3 = null;
  NodeToken n4 = null;
  Token n5 = null;
  NodeToken n6 = null;
  Token n7 = null;
  MultiplicativeExpression n8 = null;
    n0 = MultiplicativeExpression();
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PLUS:
      case MINUS:
        ;
        break;
      default:
        jj_la1[10] = jj_gen;
        break label_3;
      }
      n2 = new NodeSequence(2);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PLUS:
        n5 = jj_consume_token(PLUS);
          n4 = JTBToolkit.makeNodeToken(n5);
          n3 = new NodeChoice(n4, 0, 2);
        break;
      case MINUS:
        n7 = jj_consume_token(MINUS);
          n6 = JTBToolkit.makeNodeToken(n7);
          n3 = new NodeChoice(n6, 1, 2);
        break;
      default:
        jj_la1[11] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      n2.addNode(n3);
      n8 = MultiplicativeExpression();
      n2.addNode(n8);
      n1.addNode(n2);
    }
    n1.nodes.trimToSize();
    {if (true) return new AdditiveExpression(n0, n1);}
    throw new Error("Missing return statement in function");
  }

  final public MultiplicativeExpression MultiplicativeExpression() throws ParseException {
  // --- JTB generated node declarations ---
  PowerExpression n0 = null;
  NodeListOptional n1 = new NodeListOptional();
  NodeSequence n2 = null;
  NodeChoice n3 = null;
  NodeToken n4 = null;
  Token n5 = null;
  NodeToken n6 = null;
  Token n7 = null;
  PowerExpression n8 = null;
    n0 = PowerExpression();
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case TIMES:
      case DIV:
        ;
        break;
      default:
        jj_la1[12] = jj_gen;
        break label_4;
      }
      n2 = new NodeSequence(2);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case TIMES:
        n5 = jj_consume_token(TIMES);
          n4 = JTBToolkit.makeNodeToken(n5);
          n3 = new NodeChoice(n4, 0, 2);
        break;
      case DIV:
        n7 = jj_consume_token(DIV);
          n6 = JTBToolkit.makeNodeToken(n7);
          n3 = new NodeChoice(n6, 1, 2);
        break;
      default:
        jj_la1[13] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      n2.addNode(n3);
      n8 = PowerExpression();
      n2.addNode(n8);
      n1.addNode(n2);
    }
    n1.nodes.trimToSize();
    {if (true) return new MultiplicativeExpression(n0, n1);}
    throw new Error("Missing return statement in function");
  }

  final public PowerExpression PowerExpression() throws ParseException {
  // --- JTB generated node declarations ---
  UnaryExpression n0 = null;
  NodeListOptional n1 = new NodeListOptional();
  NodeSequence n2 = null;
  NodeSequence n3 = null;
  NodeToken n4 = null;
  Token n5 = null;
  UnaryExpression n6 = null;
    n0 = UnaryExpression();
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case CARET:
        ;
        break;
      default:
        jj_la1[14] = jj_gen;
        break label_5;
      }
      n2 = new NodeSequence(2);
        n3 = new NodeSequence(1);
      n5 = jj_consume_token(CARET);
        n4 = JTBToolkit.makeNodeToken(n5);
        n3.addNode(n4);
      n2.addNode(n3);
      n6 = UnaryExpression();
      n2.addNode(n6);
      n1.addNode(n2);
    }
    n1.nodes.trimToSize();
    {if (true) return new PowerExpression(n0, n1);}
    throw new Error("Missing return statement in function");
  }

  final public UnaryExpression UnaryExpression() throws ParseException {
  // --- JTB generated node declarations ---
  NodeChoice n0 = null;
  NodeSequence n1 = null;
  NodeChoice n2 = null;
  NodeToken n3 = null;
  Token n4 = null;
  NodeToken n5 = null;
  Token n6 = null;
  UnaryExpression n7 = null;
  UnaryExpressionNotPlusMinus n8 = null;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case PLUS:
    case MINUS:
      n1 = new NodeSequence(2);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PLUS:
        n4 = jj_consume_token(PLUS);
          n3 = JTBToolkit.makeNodeToken(n4);
          n2 = new NodeChoice(n3, 0, 2);
        break;
      case MINUS:
        n6 = jj_consume_token(MINUS);
          n5 = JTBToolkit.makeNodeToken(n6);
          n2 = new NodeChoice(n5, 1, 2);
        break;
      default:
        jj_la1[15] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      n1.addNode(n2);
      n7 = UnaryExpression();
      n1.addNode(n7);
      n0 = new NodeChoice(n1, 0, 2);
      break;
    case IF:
    case FALSE:
    case TRUE:
    case TIME:
    case TYPE_PAR:
    case TYPE_VAR:
    case TYPE_SUB:
    case TYPE_PROD:
    case TYPE_MOD:
    case TYPE_SITE:
    case TYPE_VOL:
    case TYPE_TIME:
    case SUM:
    case DELAY:
    case FLOOR:
    case CEIL:
    case COS:
    case SIN:
    case TAN:
    case TANH:
    case COSH:
    case EXP:
    case LOG:
    case LOG10:
    case ABS:
    case PI:
    case NAN:
    case CONST_AVOGADRO:
    case CONST_QUANTITY_CONV_FACTOR:
    case CONST_MODEL_TIME:
    case CONST_MODEL_TIME_INITIAL:
    case INTEGER_LITERAL:
    case FLOATING_POINT_LITERAL:
    case LPAREN:
    case BANG:
    case IDENTIFIER:
      n8 = UnaryExpressionNotPlusMinus();
      n0 = new NodeChoice(n8, 1, 2);
      break;
    default:
      jj_la1[16] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    {if (true) return new UnaryExpression(n0);}
    throw new Error("Missing return statement in function");
  }

  final public UnaryExpressionNotPlusMinus UnaryExpressionNotPlusMinus() throws ParseException {
  // --- JTB generated node declarations ---
  NodeChoice n0 = null;
  NodeSequence n1 = null;
  NodeToken n2 = null;
  Token n3 = null;
  UnaryExpression n4 = null;
  PrimaryExpression n5 = null;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case BANG:
      n1 = new NodeSequence(2);
      n3 = jj_consume_token(BANG);
      n2 = JTBToolkit.makeNodeToken(n3);
      n1.addNode(n2);
      n4 = UnaryExpression();
      n1.addNode(n4);
      n0 = new NodeChoice(n1, 0, 2);
      break;
    case IF:
    case FALSE:
    case TRUE:
    case TIME:
    case TYPE_PAR:
    case TYPE_VAR:
    case TYPE_SUB:
    case TYPE_PROD:
    case TYPE_MOD:
    case TYPE_SITE:
    case TYPE_VOL:
    case TYPE_TIME:
    case SUM:
    case DELAY:
    case FLOOR:
    case CEIL:
    case COS:
    case SIN:
    case TAN:
    case TANH:
    case COSH:
    case EXP:
    case LOG:
    case LOG10:
    case ABS:
    case PI:
    case NAN:
    case CONST_AVOGADRO:
    case CONST_QUANTITY_CONV_FACTOR:
    case CONST_MODEL_TIME:
    case CONST_MODEL_TIME_INITIAL:
    case INTEGER_LITERAL:
    case FLOATING_POINT_LITERAL:
    case LPAREN:
    case IDENTIFIER:
      n5 = PrimaryExpression();
      n0 = new NodeChoice(n5, 1, 2);
      break;
    default:
      jj_la1[17] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    {if (true) return new UnaryExpressionNotPlusMinus(n0);}
    throw new Error("Missing return statement in function");
  }

  final public PrimaryExpression PrimaryExpression() throws ParseException {
  // --- JTB generated node declarations ---
  PrimaryPrefix n0 = null;
    n0 = PrimaryPrefix();
    {if (true) return new PrimaryExpression(n0);}
    throw new Error("Missing return statement in function");
  }

  final public PrimaryPrefix PrimaryPrefix() throws ParseException {
  // --- JTB generated node declarations ---
  NodeChoice n0 = null;
  Literal n1 = null;
  NodeSequence n2 = null;
  NodeToken n3 = null;
  Token n4 = null;
  Expression n5 = null;
  NodeToken n6 = null;
  Token n7 = null;
  SpeciesReferenceOrFunctionCall n8 = null;
  MultistateSum n9 = null;
  IfExpression n10 = null;
  NodeToken n11 = null;
  Token n12 = null;
  NodeToken n13 = null;
  Token n14 = null;
  NodeToken n15 = null;
  Token n16 = null;
  NodeToken n17 = null;
  Token n18 = null;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case FALSE:
    case TRUE:
    case INTEGER_LITERAL:
    case FLOATING_POINT_LITERAL:
      n1 = Literal();
      n0 = new NodeChoice(n1, 0, 9);
      break;
    case LPAREN:
      n2 = new NodeSequence(3);
      n4 = jj_consume_token(LPAREN);
      n3 = JTBToolkit.makeNodeToken(n4);
      n2.addNode(n3);
      n5 = Expression();
      n2.addNode(n5);
      n7 = jj_consume_token(RPAREN);
      n6 = JTBToolkit.makeNodeToken(n7);
      n2.addNode(n6);
      n0 = new NodeChoice(n2, 1, 9);
      break;
    case TIME:
    case TYPE_PAR:
    case TYPE_VAR:
    case TYPE_SUB:
    case TYPE_PROD:
    case TYPE_MOD:
    case TYPE_SITE:
    case TYPE_VOL:
    case TYPE_TIME:
    case DELAY:
    case FLOOR:
    case CEIL:
    case COS:
    case SIN:
    case TAN:
    case TANH:
    case COSH:
    case EXP:
    case LOG:
    case LOG10:
    case ABS:
    case PI:
    case NAN:
    case IDENTIFIER:
      n8 = SpeciesReferenceOrFunctionCall();
      n0 = new NodeChoice(n8, 2, 9);
      break;
    case SUM:
      n9 = MultistateSum();
      n0 = new NodeChoice(n9, 3, 9);
      break;
    case IF:
      n10 = IfExpression();
      n0 = new NodeChoice(n10, 4, 9);
      break;
    case CONST_MODEL_TIME:
      n12 = jj_consume_token(CONST_MODEL_TIME);
      n11 = JTBToolkit.makeNodeToken(n12);
      n0 = new NodeChoice(n11, 5, 9);
      break;
    case CONST_AVOGADRO:
      n14 = jj_consume_token(CONST_AVOGADRO);
      n13 = JTBToolkit.makeNodeToken(n14);
      n0 = new NodeChoice(n13, 6, 9);
      break;
    case CONST_QUANTITY_CONV_FACTOR:
      n16 = jj_consume_token(CONST_QUANTITY_CONV_FACTOR);
      n15 = JTBToolkit.makeNodeToken(n16);
      n0 = new NodeChoice(n15, 7, 9);
      break;
    case CONST_MODEL_TIME_INITIAL:
      n18 = jj_consume_token(CONST_MODEL_TIME_INITIAL);
      n17 = JTBToolkit.makeNodeToken(n18);
      n0 = new NodeChoice(n17, 8, 9);
      break;
    default:
      jj_la1[18] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    {if (true) return new PrimaryPrefix(n0);}
    throw new Error("Missing return statement in function");
  }

  final public MultistateSum MultistateSum() throws ParseException {
  // --- JTB generated node declarations ---
  NodeToken n0 = null;
  Token n1 = null;
  NodeToken n2 = null;
  Token n3 = null;
  ArgumentList_MultistateSum n4 = null;
  NodeToken n5 = null;
  Token n6 = null;
    n1 = jj_consume_token(SUM);
    n0 = JTBToolkit.makeNodeToken(n1);
    n3 = jj_consume_token(LPAREN);
    n2 = JTBToolkit.makeNodeToken(n3);
    n4 = ArgumentList_MultistateSum();
    n6 = jj_consume_token(RPAREN);
    n5 = JTBToolkit.makeNodeToken(n6);
    {if (true) return new MultistateSum(n0, n2, n4, n5);}
    throw new Error("Missing return statement in function");
  }

  final public Name Name() throws ParseException {
  // --- JTB generated node declarations ---
  NodeChoice n0 = null;
  NodeSequence n1 = null;
  NodeToken n2 = null;
  Token n3 = null;
  NodeOptional n4 = new NodeOptional();
  PossibleExtensions n5 = null;
  PrimitiveType n6 = null;
  NodeToken n7 = null;
  Token n8 = null;
  NodeToken n9 = null;
  Token n10 = null;
  NodeToken n11 = null;
  Token n12 = null;
  NodeToken n13 = null;
  Token n14 = null;
  NodeToken n15 = null;
  Token n16 = null;
  NodeToken n17 = null;
  Token n18 = null;
  NodeToken n19 = null;
  Token n20 = null;
  NodeToken n21 = null;
  Token n22 = null;
  NodeToken n23 = null;
  Token n24 = null;
  NodeToken n25 = null;
  Token n26 = null;
  NodeToken n27 = null;
  Token n28 = null;
  NodeToken n29 = null;
  Token n30 = null;
  NodeToken n31 = null;
  Token n32 = null;
  NodeToken n33 = null;
  Token n34 = null;
  NodeToken n35 = null;
  Token n36 = null;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IDENTIFIER:
      n1 = new NodeSequence(2);
      n3 = jj_consume_token(IDENTIFIER);
      n2 = JTBToolkit.makeNodeToken(n3);
      n1.addNode(n2);
      if (jj_2_3(2)) {
        n5 = PossibleExtensions();
        n4.addNode(n5);
      } else {
        ;
      }
      n1.addNode(n4);
      n0 = new NodeChoice(n1, 0, 17);
      break;
    case TYPE_PAR:
    case TYPE_VAR:
    case TYPE_SUB:
    case TYPE_PROD:
    case TYPE_MOD:
    case TYPE_SITE:
    case TYPE_VOL:
    case TYPE_TIME:
      n6 = PrimitiveType();
      n0 = new NodeChoice(n6, 1, 17);
      break;
    case PI:
      n8 = jj_consume_token(PI);
      n7 = JTBToolkit.makeNodeToken(n8);
      n0 = new NodeChoice(n7, 2, 17);
      break;
    case TIME:
      n10 = jj_consume_token(TIME);
      n9 = JTBToolkit.makeNodeToken(n10);
      n0 = new NodeChoice(n9, 3, 17);
      break;
    case FLOOR:
      n12 = jj_consume_token(FLOOR);
      n11 = JTBToolkit.makeNodeToken(n12);
      n0 = new NodeChoice(n11, 4, 17);
      break;
    case DELAY:
      n14 = jj_consume_token(DELAY);
      n13 = JTBToolkit.makeNodeToken(n14);
      n0 = new NodeChoice(n13, 5, 17);
      break;
    case CEIL:
      n16 = jj_consume_token(CEIL);
      n15 = JTBToolkit.makeNodeToken(n16);
      n0 = new NodeChoice(n15, 6, 17);
      break;
    case TAN:
      n18 = jj_consume_token(TAN);
      n17 = JTBToolkit.makeNodeToken(n18);
      n0 = new NodeChoice(n17, 7, 17);
      break;
    case TANH:
      n20 = jj_consume_token(TANH);
      n19 = JTBToolkit.makeNodeToken(n20);
      n0 = new NodeChoice(n19, 8, 17);
      break;
    case COSH:
      n22 = jj_consume_token(COSH);
      n21 = JTBToolkit.makeNodeToken(n22);
      n0 = new NodeChoice(n21, 9, 17);
      break;
    case LOG10:
      n24 = jj_consume_token(LOG10);
      n23 = JTBToolkit.makeNodeToken(n24);
      n0 = new NodeChoice(n23, 10, 17);
      break;
    case ABS:
      n26 = jj_consume_token(ABS);
      n25 = JTBToolkit.makeNodeToken(n26);
      n0 = new NodeChoice(n25, 11, 17);
      break;
    case COS:
      n28 = jj_consume_token(COS);
      n27 = JTBToolkit.makeNodeToken(n28);
      n0 = new NodeChoice(n27, 12, 17);
      break;
    case SIN:
      n30 = jj_consume_token(SIN);
      n29 = JTBToolkit.makeNodeToken(n30);
      n0 = new NodeChoice(n29, 13, 17);
      break;
    case LOG:
      n32 = jj_consume_token(LOG);
      n31 = JTBToolkit.makeNodeToken(n32);
      n0 = new NodeChoice(n31, 14, 17);
      break;
    case EXP:
      n34 = jj_consume_token(EXP);
      n33 = JTBToolkit.makeNodeToken(n34);
      n0 = new NodeChoice(n33, 15, 17);
      break;
    case NAN:
      n36 = jj_consume_token(NAN);
      n35 = JTBToolkit.makeNodeToken(n36);
      n0 = new NodeChoice(n35, 16, 17);
      break;
    default:
      jj_la1[19] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    {if (true) return new Name(n0);}
    throw new Error("Missing return statement in function");
  }

  final public SpeciesReferenceOrFunctionCall_prefix SpeciesReferenceOrFunctionCall_prefix() throws ParseException {
  // --- JTB generated node declarations ---
  Name n0 = null;
  NodeOptional n1 = new NodeOptional();
  NodeSequence n2 = null;
  NodeToken n3 = null;
  Token n4 = null;
  NodeOptional n5 = null;
  ArgumentList n6 = null;
  NodeToken n7 = null;
  Token n8 = null;
    n0 = Name();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case LPAREN:
      n5 = new NodeOptional();
      n2 = new NodeSequence(3);
      n4 = jj_consume_token(LPAREN);
      n3 = JTBToolkit.makeNodeToken(n4);
      n2.addNode(n3);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IF:
      case FALSE:
      case TRUE:
      case TIME:
      case TYPE_PAR:
      case TYPE_VAR:
      case TYPE_SUB:
      case TYPE_PROD:
      case TYPE_MOD:
      case TYPE_SITE:
      case TYPE_VOL:
      case TYPE_TIME:
      case SUM:
      case DELAY:
      case FLOOR:
      case CEIL:
      case COS:
      case SIN:
      case TAN:
      case TANH:
      case COSH:
      case EXP:
      case LOG:
      case LOG10:
      case ABS:
      case PI:
      case NAN:
      case CONST_AVOGADRO:
      case CONST_QUANTITY_CONV_FACTOR:
      case CONST_MODEL_TIME:
      case CONST_MODEL_TIME_INITIAL:
      case INTEGER_LITERAL:
      case FLOATING_POINT_LITERAL:
      case LPAREN:
      case PLUS:
      case MINUS:
      case BANG:
      case IDENTIFIER:
        n6 = ArgumentList();
        n5.addNode(n6);
        break;
      default:
        jj_la1[20] = jj_gen;
        ;
      }
      n2.addNode(n5);
      n8 = jj_consume_token(RPAREN);
      n7 = JTBToolkit.makeNodeToken(n8);
      n2.addNode(n7);
      n1.addNode(n2);
      break;
    default:
      jj_la1[21] = jj_gen;
      ;
    }
    {if (true) return new SpeciesReferenceOrFunctionCall_prefix(n0, n1);}
    throw new Error("Missing return statement in function");
  }

  final public SpeciesReferenceOrFunctionCall SpeciesReferenceOrFunctionCall() throws ParseException {
  // --- JTB generated node declarations ---
  SpeciesReferenceOrFunctionCall_prefix n0 = null;
  NodeListOptional n1 = new NodeListOptional();
  NodeSequence n2 = null;
  PossibleExtensions n3 = null;
    n0 = SpeciesReferenceOrFunctionCall_prefix();
    label_6:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case EXTENSION_CONC:
      case EXTENSION_PARTICLE:
      case EXTENSION_TRANS:
      case EXTENSION_INIT:
      case EXTENSION_RATE:
      case EXTENSION_SPECIES:
      case EXTENSION_GLOBALQ:
      case EXTENSION_COMPARTMENT:
      case EXTENSION_REACTION:
      case EXTENSION_FUNCTION:
      case EXTENSION_FLUX:
      case MY_SPECIAL_EXTENSION:
        ;
        break;
      default:
        jj_la1[22] = jj_gen;
        break label_6;
      }
        n2 = new NodeSequence(1);
      n3 = PossibleExtensions();
        n2.addNode(n3);
      n1.addNode(n2);
    }
    n1.nodes.trimToSize();
    {if (true) return new SpeciesReferenceOrFunctionCall(n0, n1);}
    throw new Error("Missing return statement in function");
  }

  final public PossibleExtensions PossibleExtensions() throws ParseException {
  // --- JTB generated node declarations ---
  NodeChoice n0 = null;
  NodeToken n1 = null;
  Token n2 = null;
  NodeToken n3 = null;
  Token n4 = null;
  NodeToken n5 = null;
  Token n6 = null;
  NodeToken n7 = null;
  Token n8 = null;
  NodeToken n9 = null;
  Token n10 = null;
  NodeToken n11 = null;
  Token n12 = null;
  NodeToken n13 = null;
  Token n14 = null;
  NodeToken n15 = null;
  Token n16 = null;
  NodeToken n17 = null;
  Token n18 = null;
  NodeToken n19 = null;
  Token n20 = null;
  NodeToken n21 = null;
  Token n22 = null;
  NodeToken n23 = null;
  Token n24 = null;
  NodeListOptional n25 = new NodeListOptional();
  PossibleExtensions n26 = null;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case EXTENSION_CONC:
      n2 = jj_consume_token(EXTENSION_CONC);
        n1 = JTBToolkit.makeNodeToken(n2);
        n0 = new NodeChoice(n1, 0, 12);
      break;
    case EXTENSION_COMPARTMENT:
      n4 = jj_consume_token(EXTENSION_COMPARTMENT);
        n3 = JTBToolkit.makeNodeToken(n4);
        n0 = new NodeChoice(n3, 1, 12);
      break;
    case EXTENSION_PARTICLE:
      n6 = jj_consume_token(EXTENSION_PARTICLE);
        n5 = JTBToolkit.makeNodeToken(n6);
        n0 = new NodeChoice(n5, 2, 12);
      break;
    case EXTENSION_TRANS:
      n8 = jj_consume_token(EXTENSION_TRANS);
        n7 = JTBToolkit.makeNodeToken(n8);
        n0 = new NodeChoice(n7, 3, 12);
      break;
    case EXTENSION_INIT:
      n10 = jj_consume_token(EXTENSION_INIT);
        n9 = JTBToolkit.makeNodeToken(n10);
        n0 = new NodeChoice(n9, 4, 12);
      break;
    case EXTENSION_RATE:
      n12 = jj_consume_token(EXTENSION_RATE);
        n11 = JTBToolkit.makeNodeToken(n12);
        n0 = new NodeChoice(n11, 5, 12);
      break;
    case EXTENSION_SPECIES:
      n14 = jj_consume_token(EXTENSION_SPECIES);
        n13 = JTBToolkit.makeNodeToken(n14);
        n0 = new NodeChoice(n13, 6, 12);
      break;
    case EXTENSION_GLOBALQ:
      n16 = jj_consume_token(EXTENSION_GLOBALQ);
        n15 = JTBToolkit.makeNodeToken(n16);
        n0 = new NodeChoice(n15, 7, 12);
      break;
    case EXTENSION_FUNCTION:
      n18 = jj_consume_token(EXTENSION_FUNCTION);
        n17 = JTBToolkit.makeNodeToken(n18);
        n0 = new NodeChoice(n17, 8, 12);
      break;
    case EXTENSION_REACTION:
      n20 = jj_consume_token(EXTENSION_REACTION);
        n19 = JTBToolkit.makeNodeToken(n20);
        n0 = new NodeChoice(n19, 9, 12);
      break;
    case EXTENSION_FLUX:
      n22 = jj_consume_token(EXTENSION_FLUX);
        n21 = JTBToolkit.makeNodeToken(n22);
        n0 = new NodeChoice(n21, 10, 12);
      break;
    case MY_SPECIAL_EXTENSION:
      n24 = jj_consume_token(MY_SPECIAL_EXTENSION);
        n23 = JTBToolkit.makeNodeToken(n24);
        n0 = new NodeChoice(n23, 11, 12);
      break;
    default:
      jj_la1[23] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    label_7:
    while (true) {
      if (jj_2_4(2)) {
        ;
      } else {
        break label_7;
      }
      n26 = PossibleExtensions();
      n25.addNode(n26);
    }
    n25.nodes.trimToSize();
    {if (true) return new PossibleExtensions(n0, n25);}
    throw new Error("Missing return statement in function");
  }

  final public Literal Literal() throws ParseException {
  // --- JTB generated node declarations ---
  NodeChoice n0 = null;
  NodeToken n1 = null;
  Token n2 = null;
  NodeToken n3 = null;
  Token n4 = null;
  BooleanLiteral n5 = null;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case INTEGER_LITERAL:
      n2 = jj_consume_token(INTEGER_LITERAL);
      n1 = JTBToolkit.makeNodeToken(n2);
      n0 = new NodeChoice(n1, 0, 3);
      break;
    case FLOATING_POINT_LITERAL:
      n4 = jj_consume_token(FLOATING_POINT_LITERAL);
      n3 = JTBToolkit.makeNodeToken(n4);
      n0 = new NodeChoice(n3, 1, 3);
      break;
    case FALSE:
    case TRUE:
      n5 = BooleanLiteral();
      n0 = new NodeChoice(n5, 2, 3);
      break;
    default:
      jj_la1[24] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    {if (true) return new Literal(n0);}
    throw new Error("Missing return statement in function");
  }

  final public BooleanLiteral BooleanLiteral() throws ParseException {
  // --- JTB generated node declarations ---
  NodeChoice n0 = null;
  NodeToken n1 = null;
  Token n2 = null;
  NodeToken n3 = null;
  Token n4 = null;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case TRUE:
      n2 = jj_consume_token(TRUE);
      n1 = JTBToolkit.makeNodeToken(n2);
      n0 = new NodeChoice(n1, 0, 2);
      break;
    case FALSE:
      n4 = jj_consume_token(FALSE);
      n3 = JTBToolkit.makeNodeToken(n4);
      n0 = new NodeChoice(n3, 1, 2);
      break;
    default:
      jj_la1[25] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    {if (true) return new BooleanLiteral(n0);}
    throw new Error("Missing return statement in function");
  }

  final public ArgumentList ArgumentList() throws ParseException {
  // --- JTB generated node declarations ---
  NodeChoice n0 = null;
  NodeSequence n1 = null;
  AdditiveExpression n2 = null;
  NodeListOptional n3 = new NodeListOptional();
  NodeSequence n4 = null;
  NodeToken n5 = null;
  Token n6 = null;
  AdditiveExpression n7 = null;
  MultistateSites_list n8 = null;
    if (jj_2_5(2)) {
      n1 = new NodeSequence(2);
      n2 = AdditiveExpression();
      n1.addNode(n2);
      label_8:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case COMMA:
          ;
          break;
        default:
          jj_la1[26] = jj_gen;
          break label_8;
        }
        n4 = new NodeSequence(2);
        n6 = jj_consume_token(COMMA);
        n5 = JTBToolkit.makeNodeToken(n6);
        n4.addNode(n5);
        n7 = AdditiveExpression();
        n4.addNode(n7);
        n3.addNode(n4);
      }
      n3.nodes.trimToSize();
      n1.addNode(n3);
      n0 = new NodeChoice(n1, 0, 2);
    } else {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case TIME:
      case TYPE_PAR:
      case TYPE_VAR:
      case TYPE_SUB:
      case TYPE_PROD:
      case TYPE_MOD:
      case TYPE_SITE:
      case TYPE_VOL:
      case TYPE_TIME:
      case DELAY:
      case FLOOR:
      case CEIL:
      case COS:
      case SIN:
      case TAN:
      case TANH:
      case COSH:
      case EXP:
      case LOG:
      case LOG10:
      case ABS:
      case PI:
      case NAN:
      case IDENTIFIER:
        n8 = MultistateSites_list();
      n0 = new NodeChoice(n8, 1, 2);
        break;
      default:
        jj_la1[27] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    {if (true) return new ArgumentList(n0);}
    throw new Error("Missing return statement in function");
  }

  final public ArgumentList_MultistateSum ArgumentList_MultistateSum() throws ParseException {
  // --- JTB generated node declarations ---
  Name n0 = null;
  NodeOptional n1 = new NodeOptional();
  ArgumentList_MultistateSum_Selectors n2 = null;
    n0 = Name();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case SEMICOLON:
      n2 = ArgumentList_MultistateSum_Selectors();
      n1.addNode(n2);
      break;
    default:
      jj_la1[28] = jj_gen;
      ;
    }
    {if (true) return new ArgumentList_MultistateSum(n0, n1);}
    throw new Error("Missing return statement in function");
  }

  final public ArgumentList_MultistateSum_Selectors ArgumentList_MultistateSum_Selectors() throws ParseException {
  // --- JTB generated node declarations ---
  NodeToken n0 = null;
  Token n1 = null;
  Selector n2 = null;
  NodeListOptional n3 = new NodeListOptional();
  NodeSequence n4 = null;
  NodeToken n5 = null;
  Token n6 = null;
  Selector n7 = null;
    n1 = jj_consume_token(SEMICOLON);
    n0 = JTBToolkit.makeNodeToken(n1);
    n2 = Selector();
    label_9:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case SEMICOLON:
        ;
        break;
      default:
        jj_la1[29] = jj_gen;
        break label_9;
      }
      n4 = new NodeSequence(2);
      n6 = jj_consume_token(SEMICOLON);
      n5 = JTBToolkit.makeNodeToken(n6);
      n4.addNode(n5);
      n7 = Selector();
      n4.addNode(n7);
      n3.addNode(n4);
    }
    n3.nodes.trimToSize();
    {if (true) return new ArgumentList_MultistateSum_Selectors(n0, n2, n3);}
    throw new Error("Missing return statement in function");
  }

  final public Selector Selector() throws ParseException {
  // --- JTB generated node declarations ---
  Name n0 = null;
  NodeOptional n1 = new NodeOptional();
  NodeChoice n2 = null;
  SiteSelector_postFix n3 = null;
  CoeffFunction_postFix n4 = null;
    n0 = Name();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case LPAREN:
    case LBRACE:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LBRACE:
        n3 = SiteSelector_postFix();
        n2 = new NodeChoice(n3, 0, 2);
        break;
      case LPAREN:
        n4 = CoeffFunction_postFix();
        n2 = new NodeChoice(n4, 1, 2);
        break;
      default:
        jj_la1[30] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      n1.addNode(n2);
      break;
    default:
      jj_la1[31] = jj_gen;
      ;
    }
    {if (true) return new Selector(n0, n1);}
    throw new Error("Missing return statement in function");
  }

  final public SiteSelector_postFix SiteSelector_postFix() throws ParseException {
  // --- JTB generated node declarations ---
  NodeToken n0 = null;
  Token n1 = null;
  NodeChoice n2 = null;
  Name n3 = null;
  Literal n4 = null;
  NodeOptional n5 = new NodeOptional();
  NodeChoice n6 = null;
  NodeList n7 = null;
  NodeSequence n8 = null;
  NodeToken n9 = null;
  Token n10 = null;
  NodeChoice n11 = null;
  Name n12 = null;
  Literal n13 = null;
  NodeSequence n14 = null;
  NodeToken n15 = null;
  Token n16 = null;
  NodeChoice n17 = null;
  Name n18 = null;
  Literal n19 = null;
  NodeToken n20 = null;
  Token n21 = null;
    n1 = jj_consume_token(LBRACE);
    n0 = JTBToolkit.makeNodeToken(n1);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case TIME:
    case TYPE_PAR:
    case TYPE_VAR:
    case TYPE_SUB:
    case TYPE_PROD:
    case TYPE_MOD:
    case TYPE_SITE:
    case TYPE_VOL:
    case TYPE_TIME:
    case DELAY:
    case FLOOR:
    case CEIL:
    case COS:
    case SIN:
    case TAN:
    case TANH:
    case COSH:
    case EXP:
    case LOG:
    case LOG10:
    case ABS:
    case PI:
    case NAN:
    case IDENTIFIER:
      n3 = Name();
        n2 = new NodeChoice(n3, 0, 2);
      break;
    case FALSE:
    case TRUE:
    case INTEGER_LITERAL:
    case FLOATING_POINT_LITERAL:
      n4 = Literal();
        n2 = new NodeChoice(n4, 1, 2);
      break;
    default:
      jj_la1[32] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case COMMA:
    case COLON:
      n7 = new NodeList();
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case COMMA:
        label_10:
        while (true) {
          n8 = new NodeSequence(2);
          n10 = jj_consume_token(COMMA);
          n9 = JTBToolkit.makeNodeToken(n10);
          n8.addNode(n9);
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case TIME:
          case TYPE_PAR:
          case TYPE_VAR:
          case TYPE_SUB:
          case TYPE_PROD:
          case TYPE_MOD:
          case TYPE_SITE:
          case TYPE_VOL:
          case TYPE_TIME:
          case DELAY:
          case FLOOR:
          case CEIL:
          case COS:
          case SIN:
          case TAN:
          case TANH:
          case COSH:
          case EXP:
          case LOG:
          case LOG10:
          case ABS:
          case PI:
          case NAN:
          case IDENTIFIER:
            n12 = Name();
              n11 = new NodeChoice(n12, 0, 2);
            break;
          case FALSE:
          case TRUE:
          case INTEGER_LITERAL:
          case FLOATING_POINT_LITERAL:
            n13 = Literal();
              n11 = new NodeChoice(n13, 1, 2);
            break;
          default:
            jj_la1[33] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
          }
          n8.addNode(n11);
          n7.addNode(n8);
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case COMMA:
            ;
            break;
          default:
            jj_la1[34] = jj_gen;
            break label_10;
          }
        }
        n7.nodes.trimToSize();
        n6 = new NodeChoice(n7, 0, 2);
        break;
      case COLON:
          n14 = new NodeSequence(2);
        n16 = jj_consume_token(COLON);
          n15 = JTBToolkit.makeNodeToken(n16);
          n14.addNode(n15);
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case TIME:
        case TYPE_PAR:
        case TYPE_VAR:
        case TYPE_SUB:
        case TYPE_PROD:
        case TYPE_MOD:
        case TYPE_SITE:
        case TYPE_VOL:
        case TYPE_TIME:
        case DELAY:
        case FLOOR:
        case CEIL:
        case COS:
        case SIN:
        case TAN:
        case TANH:
        case COSH:
        case EXP:
        case LOG:
        case LOG10:
        case ABS:
        case PI:
        case NAN:
        case IDENTIFIER:
          n18 = Name();
              n17 = new NodeChoice(n18, 0, 2);
          break;
        case FALSE:
        case TRUE:
        case INTEGER_LITERAL:
        case FLOATING_POINT_LITERAL:
          n19 = Literal();
              n17 = new NodeChoice(n19, 1, 2);
          break;
        default:
          jj_la1[35] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
          n14.addNode(n17);
        n6 = new NodeChoice(n14, 1, 2);
        break;
      default:
        jj_la1[36] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      n5.addNode(n6);
      break;
    default:
      jj_la1[37] = jj_gen;
      ;
    }
    n21 = jj_consume_token(RBRACE);
    n20 = JTBToolkit.makeNodeToken(n21);
    {if (true) return new SiteSelector_postFix(n0, n2, n5, n20);}
    throw new Error("Missing return statement in function");
  }

  final public CoeffFunction_postFix CoeffFunction_postFix() throws ParseException {
  // --- JTB generated node declarations ---
  NodeToken n0 = null;
  Token n1 = null;
  NodeOptional n2 = new NodeOptional();
  ArgumentList n3 = null;
  NodeToken n4 = null;
  Token n5 = null;
    n1 = jj_consume_token(LPAREN);
    n0 = JTBToolkit.makeNodeToken(n1);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IF:
    case FALSE:
    case TRUE:
    case TIME:
    case TYPE_PAR:
    case TYPE_VAR:
    case TYPE_SUB:
    case TYPE_PROD:
    case TYPE_MOD:
    case TYPE_SITE:
    case TYPE_VOL:
    case TYPE_TIME:
    case SUM:
    case DELAY:
    case FLOOR:
    case CEIL:
    case COS:
    case SIN:
    case TAN:
    case TANH:
    case COSH:
    case EXP:
    case LOG:
    case LOG10:
    case ABS:
    case PI:
    case NAN:
    case CONST_AVOGADRO:
    case CONST_QUANTITY_CONV_FACTOR:
    case CONST_MODEL_TIME:
    case CONST_MODEL_TIME_INITIAL:
    case INTEGER_LITERAL:
    case FLOATING_POINT_LITERAL:
    case LPAREN:
    case PLUS:
    case MINUS:
    case BANG:
    case IDENTIFIER:
      n3 = ArgumentList();
      n2.addNode(n3);
      break;
    default:
      jj_la1[38] = jj_gen;
      ;
    }
    n5 = jj_consume_token(RPAREN);
    n4 = JTBToolkit.makeNodeToken(n5);
    {if (true) return new CoeffFunction_postFix(n0, n2, n4);}
    throw new Error("Missing return statement in function");
  }

  final public MultistateSite MultistateSite() throws ParseException {
  // --- JTB generated node declarations ---
  Name n0 = null;
  NodeToken n1 = null;
  Token n2 = null;
  NodeChoice n3 = null;
  Name n4 = null;
  Literal n5 = null;
  NodeToken n6 = null;
  Token n7 = null;
    n0 = Name();
    n2 = jj_consume_token(LBRACE);
    n1 = JTBToolkit.makeNodeToken(n2);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case TIME:
    case TYPE_PAR:
    case TYPE_VAR:
    case TYPE_SUB:
    case TYPE_PROD:
    case TYPE_MOD:
    case TYPE_SITE:
    case TYPE_VOL:
    case TYPE_TIME:
    case DELAY:
    case FLOOR:
    case CEIL:
    case COS:
    case SIN:
    case TAN:
    case TANH:
    case COSH:
    case EXP:
    case LOG:
    case LOG10:
    case ABS:
    case PI:
    case NAN:
    case IDENTIFIER:
      n4 = Name();
        n3 = new NodeChoice(n4, 0, 2);
      break;
    case FALSE:
    case TRUE:
    case INTEGER_LITERAL:
    case FLOATING_POINT_LITERAL:
      n5 = Literal();
        n3 = new NodeChoice(n5, 1, 2);
      break;
    default:
      jj_la1[39] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    n7 = jj_consume_token(RBRACE);
    n6 = JTBToolkit.makeNodeToken(n7);
    {if (true) return new MultistateSite(n0, n1, n3, n6);}
    throw new Error("Missing return statement in function");
  }

  final public MultistateSites_list MultistateSites_list() throws ParseException {
  // --- JTB generated node declarations ---
  MultistateSite n0 = null;
  NodeListOptional n1 = new NodeListOptional();
  NodeSequence n2 = null;
  NodeToken n3 = null;
  Token n4 = null;
  MultistateSite n5 = null;
    n0 = MultistateSite();
    label_11:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case SEMICOLON:
        ;
        break;
      default:
        jj_la1[40] = jj_gen;
        break label_11;
      }
      n2 = new NodeSequence(2);
      n4 = jj_consume_token(SEMICOLON);
      n3 = JTBToolkit.makeNodeToken(n4);
      n2.addNode(n3);
      n5 = MultistateSite();
      n2.addNode(n5);
      n1.addNode(n2);
    }
    n1.nodes.trimToSize();
    {if (true) return new MultistateSites_list(n0, n1);}
    throw new Error("Missing return statement in function");
  }

  private boolean jj_2_1(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_1(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  private boolean jj_2_2(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_2(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  private boolean jj_2_3(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_3(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  private boolean jj_2_4(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_4(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  private boolean jj_2_5(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_5(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(4, xla); }
  }

  private boolean jj_3R_13() {
    if (jj_3R_15()) return true;
    return false;
  }

  private boolean jj_3R_62() {
    if (jj_scan_token(SUM)) return true;
    if (jj_scan_token(LPAREN)) return true;
    return false;
  }

  private boolean jj_3R_41() {
    if (jj_scan_token(DIV)) return true;
    return false;
  }

  private boolean jj_3R_40() {
    if (jj_scan_token(TIMES)) return true;
    return false;
  }

  private boolean jj_3R_68() {
    if (jj_3R_14()) return true;
    return false;
  }

  private boolean jj_3R_35() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_40()) {
    jj_scanpos = xsp;
    if (jj_3R_41()) return true;
    }
    return false;
  }

  private boolean jj_3R_59() {
    if (jj_scan_token(CONST_MODEL_TIME_INITIAL)) return true;
    return false;
  }

  private boolean jj_3R_61() {
    if (jj_3R_67()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_68()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_32() {
    if (jj_3R_34()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_35()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_63() {
    if (jj_scan_token(IF)) return true;
    if (jj_scan_token(LPAREN)) return true;
    return false;
  }

  private boolean jj_3R_58() {
    if (jj_scan_token(CONST_QUANTITY_CONV_FACTOR)) return true;
    return false;
  }

  private boolean jj_3R_57() {
    if (jj_scan_token(CONST_AVOGADRO)) return true;
    return false;
  }

  private boolean jj_3R_56() {
    if (jj_scan_token(CONST_MODEL_TIME)) return true;
    return false;
  }

  private boolean jj_3R_16() {
    if (jj_scan_token(COMMA)) return true;
    return false;
  }

  private boolean jj_3R_55() {
    if (jj_3R_63()) return true;
    return false;
  }

  private boolean jj_3R_54() {
    if (jj_3R_62()) return true;
    return false;
  }

  private boolean jj_3_5() {
    if (jj_3R_15()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_16()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_53() {
    if (jj_3R_61()) return true;
    return false;
  }

  private boolean jj_3R_37() {
    if (jj_scan_token(MINUS)) return true;
    return false;
  }

  private boolean jj_3R_71() {
    if (jj_scan_token(LPAREN)) return true;
    return false;
  }

  private boolean jj_3R_36() {
    if (jj_scan_token(PLUS)) return true;
    return false;
  }

  private boolean jj_3R_67() {
    if (jj_3R_70()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_71()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3R_52() {
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_13()) return true;
    return false;
  }

  private boolean jj_3R_33() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_36()) {
    jj_scanpos = xsp;
    if (jj_3R_37()) return true;
    }
    return false;
  }

  private boolean jj_3R_51() {
    if (jj_3R_60()) return true;
    return false;
  }

  private boolean jj_3R_50() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_51()) {
    jj_scanpos = xsp;
    if (jj_3R_52()) {
    jj_scanpos = xsp;
    if (jj_3R_53()) {
    jj_scanpos = xsp;
    if (jj_3R_54()) {
    jj_scanpos = xsp;
    if (jj_3R_55()) {
    jj_scanpos = xsp;
    if (jj_3R_56()) {
    jj_scanpos = xsp;
    if (jj_3R_57()) {
    jj_scanpos = xsp;
    if (jj_3R_58()) {
    jj_scanpos = xsp;
    if (jj_3R_59()) return true;
    }
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_15() {
    if (jj_3R_32()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_33()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_99() {
    if (jj_scan_token(TYPE_TIME)) return true;
    return false;
  }

  private boolean jj_3R_73() {
    if (jj_scan_token(FALSE)) return true;
    return false;
  }

  private boolean jj_3R_98() {
    if (jj_scan_token(TYPE_VOL)) return true;
    return false;
  }

  private boolean jj_3R_72() {
    if (jj_scan_token(TRUE)) return true;
    return false;
  }

  private boolean jj_3R_90() {
    if (jj_scan_token(NAN)) return true;
    return false;
  }

  private boolean jj_3R_69() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_72()) {
    jj_scanpos = xsp;
    if (jj_3R_73()) return true;
    }
    return false;
  }

  private boolean jj_3R_97() {
    if (jj_scan_token(TYPE_SITE)) return true;
    return false;
  }

  private boolean jj_3R_89() {
    if (jj_scan_token(EXP)) return true;
    return false;
  }

  private boolean jj_3R_96() {
    if (jj_scan_token(TYPE_MOD)) return true;
    return false;
  }

  private boolean jj_3R_88() {
    if (jj_scan_token(LOG)) return true;
    return false;
  }

  private boolean jj_3R_95() {
    if (jj_scan_token(TYPE_PROD)) return true;
    return false;
  }

  private boolean jj_3R_19() {
    if (jj_scan_token(XOR)) return true;
    return false;
  }

  private boolean jj_3R_87() {
    if (jj_scan_token(SIN)) return true;
    return false;
  }

  private boolean jj_3R_94() {
    if (jj_scan_token(TYPE_SUB)) return true;
    return false;
  }

  private boolean jj_3R_18() {
    if (jj_scan_token(OR)) return true;
    return false;
  }

  private boolean jj_3R_66() {
    if (jj_3R_69()) return true;
    return false;
  }

  private boolean jj_3R_86() {
    if (jj_scan_token(COS)) return true;
    return false;
  }

  private boolean jj_3R_93() {
    if (jj_scan_token(TYPE_VAR)) return true;
    return false;
  }

  private boolean jj_3R_65() {
    if (jj_scan_token(FLOATING_POINT_LITERAL)) return true;
    return false;
  }

  private boolean jj_3R_17() {
    if (jj_scan_token(AND)) return true;
    return false;
  }

  private boolean jj_3R_49() {
    if (jj_3R_50()) return true;
    return false;
  }

  private boolean jj_3R_85() {
    if (jj_scan_token(ABS)) return true;
    return false;
  }

  private boolean jj_3R_92() {
    if (jj_scan_token(TYPE_PAR)) return true;
    return false;
  }

  private boolean jj_3R_12() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_17()) {
    jj_scanpos = xsp;
    if (jj_3R_18()) {
    jj_scanpos = xsp;
    if (jj_3R_19()) return true;
    }
    }
    return false;
  }

  private boolean jj_3R_64() {
    if (jj_scan_token(INTEGER_LITERAL)) return true;
    return false;
  }

  private boolean jj_3R_91() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_92()) {
    jj_scanpos = xsp;
    if (jj_3R_93()) {
    jj_scanpos = xsp;
    if (jj_3R_94()) {
    jj_scanpos = xsp;
    if (jj_3R_95()) {
    jj_scanpos = xsp;
    if (jj_3R_96()) {
    jj_scanpos = xsp;
    if (jj_3R_97()) {
    jj_scanpos = xsp;
    if (jj_3R_98()) {
    jj_scanpos = xsp;
    if (jj_3R_99()) return true;
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_84() {
    if (jj_scan_token(LOG10)) return true;
    return false;
  }

  private boolean jj_3R_60() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_64()) {
    jj_scanpos = xsp;
    if (jj_3R_65()) {
    jj_scanpos = xsp;
    if (jj_3R_66()) return true;
    }
    }
    return false;
  }

  private boolean jj_3R_83() {
    if (jj_scan_token(COSH)) return true;
    return false;
  }

  private boolean jj_3R_48() {
    if (jj_3R_49()) return true;
    return false;
  }

  private boolean jj_3R_82() {
    if (jj_scan_token(TANH)) return true;
    return false;
  }

  private boolean jj_3R_81() {
    if (jj_scan_token(TAN)) return true;
    return false;
  }

  private boolean jj_3R_47() {
    if (jj_scan_token(BANG)) return true;
    if (jj_3R_38()) return true;
    return false;
  }

  private boolean jj_3R_46() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_47()) {
    jj_scanpos = xsp;
    if (jj_3R_48()) return true;
    }
    return false;
  }

  private boolean jj_3R_80() {
    if (jj_scan_token(CEIL)) return true;
    return false;
  }

  private boolean jj_3_4() {
    if (jj_3R_14()) return true;
    return false;
  }

  private boolean jj_3R_79() {
    if (jj_scan_token(DELAY)) return true;
    return false;
  }

  private boolean jj_3R_31() {
    if (jj_scan_token(MY_SPECIAL_EXTENSION)) return true;
    return false;
  }

  private boolean jj_3R_78() {
    if (jj_scan_token(FLOOR)) return true;
    return false;
  }

  private boolean jj_3R_30() {
    if (jj_scan_token(EXTENSION_FLUX)) return true;
    return false;
  }

  private boolean jj_3R_77() {
    if (jj_scan_token(TIME)) return true;
    return false;
  }

  private boolean jj_3R_43() {
    if (jj_3R_46()) return true;
    return false;
  }

  private boolean jj_3R_29() {
    if (jj_scan_token(EXTENSION_REACTION)) return true;
    return false;
  }

  private boolean jj_3R_76() {
    if (jj_scan_token(PI)) return true;
    return false;
  }

  private boolean jj_3_2() {
    if (jj_scan_token(ASSIGN)) return true;
    return false;
  }

  private boolean jj_3R_75() {
    if (jj_3R_91()) return true;
    return false;
  }

  private boolean jj_3R_28() {
    if (jj_scan_token(EXTENSION_FUNCTION)) return true;
    return false;
  }

  private boolean jj_3R_45() {
    if (jj_scan_token(MINUS)) return true;
    return false;
  }

  private boolean jj_3R_27() {
    if (jj_scan_token(EXTENSION_GLOBALQ)) return true;
    return false;
  }

  private boolean jj_3_3() {
    if (jj_3R_14()) return true;
    return false;
  }

  private boolean jj_3R_44() {
    if (jj_scan_token(PLUS)) return true;
    return false;
  }

  private boolean jj_3R_26() {
    if (jj_scan_token(EXTENSION_SPECIES)) return true;
    return false;
  }

  private boolean jj_3R_74() {
    if (jj_scan_token(IDENTIFIER)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_3()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3R_25() {
    if (jj_scan_token(EXTENSION_RATE)) return true;
    return false;
  }

  private boolean jj_3R_42() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_44()) {
    jj_scanpos = xsp;
    if (jj_3R_45()) return true;
    }
    if (jj_3R_38()) return true;
    return false;
  }

  private boolean jj_3R_70() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_74()) {
    jj_scanpos = xsp;
    if (jj_3R_75()) {
    jj_scanpos = xsp;
    if (jj_3R_76()) {
    jj_scanpos = xsp;
    if (jj_3R_77()) {
    jj_scanpos = xsp;
    if (jj_3R_78()) {
    jj_scanpos = xsp;
    if (jj_3R_79()) {
    jj_scanpos = xsp;
    if (jj_3R_80()) {
    jj_scanpos = xsp;
    if (jj_3R_81()) {
    jj_scanpos = xsp;
    if (jj_3R_82()) {
    jj_scanpos = xsp;
    if (jj_3R_83()) {
    jj_scanpos = xsp;
    if (jj_3R_84()) {
    jj_scanpos = xsp;
    if (jj_3R_85()) {
    jj_scanpos = xsp;
    if (jj_3R_86()) {
    jj_scanpos = xsp;
    if (jj_3R_87()) {
    jj_scanpos = xsp;
    if (jj_3R_88()) {
    jj_scanpos = xsp;
    if (jj_3R_89()) {
    jj_scanpos = xsp;
    if (jj_3R_90()) return true;
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_38() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_42()) {
    jj_scanpos = xsp;
    if (jj_3R_43()) return true;
    }
    return false;
  }

  private boolean jj_3R_24() {
    if (jj_scan_token(EXTENSION_INIT)) return true;
    return false;
  }

  private boolean jj_3R_23() {
    if (jj_scan_token(EXTENSION_TRANS)) return true;
    return false;
  }

  private boolean jj_3R_22() {
    if (jj_scan_token(EXTENSION_PARTICLE)) return true;
    return false;
  }

  private boolean jj_3R_21() {
    if (jj_scan_token(EXTENSION_COMPARTMENT)) return true;
    return false;
  }

  private boolean jj_3R_20() {
    if (jj_scan_token(EXTENSION_CONC)) return true;
    return false;
  }

  private boolean jj_3R_14() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_20()) {
    jj_scanpos = xsp;
    if (jj_3R_21()) {
    jj_scanpos = xsp;
    if (jj_3R_22()) {
    jj_scanpos = xsp;
    if (jj_3R_23()) {
    jj_scanpos = xsp;
    if (jj_3R_24()) {
    jj_scanpos = xsp;
    if (jj_3R_25()) {
    jj_scanpos = xsp;
    if (jj_3R_26()) {
    jj_scanpos = xsp;
    if (jj_3R_27()) {
    jj_scanpos = xsp;
    if (jj_3R_28()) {
    jj_scanpos = xsp;
    if (jj_3R_29()) {
    jj_scanpos = xsp;
    if (jj_3R_30()) {
    jj_scanpos = xsp;
    if (jj_3R_31()) return true;
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_4()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3_1() {
    if (jj_3R_12()) return true;
    if (jj_3R_13()) return true;
    return false;
  }

  private boolean jj_3R_39() {
    if (jj_scan_token(CARET)) return true;
    return false;
  }

  private boolean jj_3R_34() {
    if (jj_3R_38()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_39()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  /** Generated Token Manager. */
  public MR_Expression_ParserTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private Token jj_scanpos, jj_lastpos;
  private int jj_la;
  private int jj_gen;
  final private int[] jj_la1 = new int[41];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static private int[] jj_la1_2;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
      jj_la1_init_2();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x7fc0c80,0x0,0x0,0x7f80000,0x7f80000,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x7fc0c80,0x7fc0c80,0x7fc0c80,0x7fc0000,0x7fc0c80,0x0,0xf8000000,0xf8000000,0xc00,0xc00,0x0,0x7fc0000,0x0,0x0,0x0,0x0,0x7fc0c00,0x7fc0c00,0x0,0x7fc0c00,0x0,0x0,0x7fc0c80,0x7fc0c00,0x0,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x5ffeff80,0x40000000,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x5ffeff80,0x5ffeff80,0x5ffeff80,0x7eff00,0x5ffeff80,0x40000000,0x7f,0x7f,0x18000000,0x0,0x0,0x7eff00,0x0,0x0,0x40000000,0x40000000,0x187eff00,0x187eff00,0x0,0x187eff00,0x0,0x0,0x5ffeff80,0x187eff00,0x0,};
   }
   private static void jj_la1_init_2() {
      jj_la1_2 = new int[] {0x2008300,0x0,0x20,0x0,0x0,0x20,0x1c7000,0x40000,0x1c7000,0x1c00000,0x300,0x300,0xc00,0xc00,0x10000,0x300,0x2008300,0x2008000,0x2000000,0x2000000,0x2008300,0x0,0x0,0x0,0x0,0x0,0x20,0x2000000,0x10,0x10,0x1,0x1,0x2000000,0x2000000,0x20,0x2000000,0x60,0x60,0x2008300,0x2000000,0x10,};
   }
  final private JJCalls[] jj_2_rtns = new JJCalls[5];
  private boolean jj_rescan = false;
  private int jj_gc = 0;

  /** Constructor with InputStream. */
  public MR_Expression_Parser(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public MR_Expression_Parser(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new MR_Expression_ParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 41; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 41; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public MR_Expression_Parser(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new MR_Expression_ParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 41; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 41; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public MR_Expression_Parser(MR_Expression_ParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 41; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(MR_Expression_ParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 41; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  static private final class LookaheadSuccess extends java.lang.Error { }
  final private LookaheadSuccess jj_ls = new LookaheadSuccess();
  private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
    return false;
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;
  private int[] jj_lasttokens = new int[100];
  private int jj_endpos;

  private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      jj_entries_loop: for (java.util.Iterator<?> it = jj_expentries.iterator(); it.hasNext();) {
        int[] oldentry = (int[])(it.next());
        if (oldentry.length == jj_expentry.length) {
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              continue jj_entries_loop;
            }
          }
          jj_expentries.add(jj_expentry);
          break jj_entries_loop;
        }
      }
      if (pos != 0) jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[93];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 41; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
          if ((jj_la1_2[i] & (1<<j)) != 0) {
            la1tokens[64+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 93; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

  private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 5; i++) {
    try {
      JJCalls p = jj_2_rtns[i];
      do {
        if (p.gen > jj_gen) {
          jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
          switch (i) {
            case 0: jj_3_1(); break;
            case 1: jj_3_2(); break;
            case 2: jj_3_3(); break;
            case 3: jj_3_4(); break;
            case 4: jj_3_5(); break;
          }
        }
        p = p.next;
      } while (p != null);
      } catch(LookaheadSuccess ls) { }
    }
    jj_rescan = false;
  }

  private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; p.first = token; p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

}


class MyVisitor extends DepthFirstVoidVisitor {

  public void visit(NodeToken n) {
    System.out.println("visit " + MR_Expression_ParserConstants.tokenImage[n.kind] + "-->" + n.tokenImage);
  }
}

class JTBToolkit {

  static NodeToken makeNodeToken(final Token t) {
    return new NodeToken(t.image.intern(), t.kind, t.beginLine, t.beginColumn, t.endLine, t.endColumn);
  }
}
