/* Generated by JTB 1.4.4 */
package parsers.chemicalReaction.visitor;

import parsers.chemicalReaction.syntaxtree.*;
import java.util.*;

/**
 * Provides default methods which visit each node in the tree in depth-first order.<br>
 * In your "VoidArgu" visitors extend this class and override part or all of these methods.
 *
 * @param <A> The user argument type
 */
public class DepthFirstVoidArguVisitor<A> implements IVoidArguVisitor<A> {


  /*
   * Base nodes classes visit methods (to be overridden if necessary)
   */

  /**
   * Visits a {@link NodeChoice} node, passing it an argument.
   *
   * @param n the node to visit
   * @param argu the user argument
   */
  public void visit(final NodeChoice n, final A argu) {
    n.choice.accept(this, argu);
    return;
  }

  /**
   * Visits a {@link NodeList} node, passing it an argument.
   *
   * @param n the node to visit
   * @param argu the user argument
   */
  public void visit(final NodeList n, final A argu) {
    for (final Iterator<INode> e = n.elements(); e.hasNext();) {
      e.next().accept(this, argu);
    }
    return;
  }

  /**
   * Visits a {@link NodeListOptional} node, passing it an argument.
   *
   * @param n the node to visit
   * @param argu the user argument
   */
  public void visit(final NodeListOptional n, final A argu) {
    if (n.present()) {
      for (final Iterator<INode> e = n.elements(); e.hasNext();) {
        e.next().accept(this, argu);
        }
      return;
    } else
      return;
  }

  /**
   * Visits a {@link NodeOptional} node, passing it an argument.
   *
   * @param n the node to visit
   * @param argu the user argument
   */
  public void visit(final NodeOptional n, final A argu) {
    if (n.present()) {
      n.node.accept(this, argu);
      return;
    } else
    return;
  }

  /**
   * Visits a {@link NodeSequence} node, passing it an argument.
   *
   * @param n the node to visit
   * @param argu the user argument
   */
  public void visit(final NodeSequence n, final A argu) {
    for (final Iterator<INode> e = n.elements(); e.hasNext();) {
      e.next().accept(this, argu);
    }
    return;
  }

  /**
   * Visits a {@link NodeToken} node, passing it an argument.
   *
   * @param n the node to visit
   * @param argu the user argument
   */
  public void visit(final NodeToken n, @SuppressWarnings("unused") final A argu) {
    @SuppressWarnings("unused")
    final String tkIm = n.tokenImage;
    return;
  }

  /*
   * User grammar generated visit methods (to be overridden if necessary)
   */

  /**
   * Visits a {@link CompleteReaction} node, whose children are the following :
   * <p>
   * reaction -> Reaction()<br>
   * nodeToken -> < EOF ><br>
   *
   * @param n the node to visit
   * @param argu the user argument
   */
  public void visit(final CompleteReaction n, final A argu) {
    // reaction -> Reaction()
    n.reaction.accept(this, argu);
    // nodeToken -> < EOF >
    n.nodeToken.accept(this, argu);
  }

  /**
   * Visits a {@link CompleteSpeciesWithCoefficient} node, whose children are the following :
   * <p>
   * speciesWithCoeff -> SpeciesWithCoeff()<br>
   * nodeToken -> < EOF ><br>
   *
   * @param n the node to visit
   * @param argu the user argument
   */
  public void visit(final CompleteSpeciesWithCoefficient n, final A argu) {
    // speciesWithCoeff -> SpeciesWithCoeff()
    n.speciesWithCoeff.accept(this, argu);
    // nodeToken -> < EOF >
    n.nodeToken.accept(this, argu);
  }

  /**
   * Visits a {@link Reaction} node, whose children are the following :
   * <p>
   * nodeChoice -> . %0 #0 ( AdditiveExpression() )?<br>
   * .......... .. . .. #1 ( Blank() )* #2 < ARROW ><br>
   * .......... .. . .. #3 ( $0 ( " " )<br>
   * .......... .. . .. .. . $1 ( Blank() )*<br>
   * .......... .. . .. .. . $2 ( AdditiveExpression() )? )*<br>
   * .......... .. . .. #4 ( $0 ( Blank() )* $1 ";"<br>
   * .......... .. . .. .. . $2 ( Blank() )* $3 ListModifiers() )?<br>
   * .......... .. | %1 #0 < ARROW2 ><br>
   * .......... .. . .. #1 ( Blank() )*<br>
   * .......... .. . .. #2 ( AdditiveExpression() )?<br>
   * .......... .. . .. #3 ( $0 ( Blank() )* $1 ";"<br>
   * .......... .. . .. .. . $2 ( Blank() )* $3 ListModifiers() )?<br>
   *
   * @param n the node to visit
   * @param argu the user argument
   */
  public void visit(final Reaction n, final A argu) {
    // nodeChoice -> . %0 #0 ( AdditiveExpression() )?
    // .......... .. . .. #1 ( Blank() )* #2 < ARROW >
    // .......... .. . .. #3 ( $0 ( " " )
    // .......... .. . .. .. . $1 ( Blank() )*
    // .......... .. . .. .. . $2 ( AdditiveExpression() )? )*
    // .......... .. . .. #4 ( $0 ( Blank() )* $1 ";"
    // .......... .. . .. .. . $2 ( Blank() )* $3 ListModifiers() )?
    // .......... .. | %1 #0 < ARROW2 >
    // .......... .. . .. #1 ( Blank() )*
    // .......... .. . .. #2 ( AdditiveExpression() )?
    // .......... .. . .. #3 ( $0 ( Blank() )* $1 ";"
    // .......... .. . .. .. . $2 ( Blank() )* $3 ListModifiers() )?
    n.nodeChoice.accept(this, argu);
  }

  /**
   * Visits a {@link AdditiveExpression} node, whose children are the following :
   * <p>
   * speciesWithCoeff -> SpeciesWithCoeff()<br>
   * nodeListOptional -> ( #0 ( Blank() )* #1 " + "<br>
   * ................ .. . #2 ( Blank() )* #3 SpeciesWithCoeff() )*<br>
   *
   * @param n the node to visit
   * @param argu the user argument
   */
  public void visit(final AdditiveExpression n, final A argu) {
    // speciesWithCoeff -> SpeciesWithCoeff()
    n.speciesWithCoeff.accept(this, argu);
    // nodeListOptional -> ( #0 ( Blank() )* #1 " + "
    // ................ .. . #2 ( Blank() )* #3 SpeciesWithCoeff() )*
    n.nodeListOptional.accept(this, argu);
  }

  /**
   * Visits a {@link SpeciesWithCoeff} node, whose children are the following :
   * <p>
   * nodeOptional -> ( #0 Stoichiometry()<br>
   * ............ .. . #1 ( Blank() )* #2 " * "<br>
   * ............ .. . #3 ( Blank() )* )?<br>
   * species -> Species()<br>
   *
   * @param n the node to visit
   * @param argu the user argument
   */
  public void visit(final SpeciesWithCoeff n, final A argu) {
    // nodeOptional -> ( #0 Stoichiometry()
    // ............ .. . #1 ( Blank() )* #2 "// "
    // ............ .. . #3 ( Blank() )* )?
    n.nodeOptional.accept(this, argu);
    // species -> Species()
    n.species.accept(this, argu);
  }

  /**
   * Visits a {@link Blank} node, whose children are the following :
   * <p>
   * nodeToken -> " "<br>
   *
   * @param n the node to visit
   * @param argu the user argument
   */
  public void visit(final Blank n, final A argu) {
    // nodeToken -> " "
    n.nodeToken.accept(this, argu);
  }

  /**
   * Visits a {@link ListModifiers} node, whose children are the following :
   * <p>
   * species -> Species()<br>
   * nodeListOptional -> ( #0 ( Blank() )+ #1 Species() )*<br>
   *
   * @param n the node to visit
   * @param argu the user argument
   */
  public void visit(final ListModifiers n, final A argu) {
    // species -> Species()
    n.species.accept(this, argu);
    // nodeListOptional -> ( #0 ( Blank() )+ #1 Species() )*
    n.nodeListOptional.accept(this, argu);
  }

  /**
   * Visits a {@link Species} node, whose children are the following :
   * <p>
   * nodeToken -> < IDENTIFIER ><br>
   * nodeListOptional -> ( < IDENTIFIER > )*<br>
   *
   * @param n the node to visit
   * @param argu the user argument
   */
  public void visit(final Species n, final A argu) {
    // nodeToken -> < IDENTIFIER >
    n.nodeToken.accept(this, argu);
    // nodeListOptional -> ( < IDENTIFIER > )*
    n.nodeListOptional.accept(this, argu);
  }

  /**
   * Visits a {@link Stoichiometry} node, whose children are the following :
   * <p>
   * nodeChoice -> . %0 < INTEGER_LITERAL ><br>
   * .......... .. | %1 < FLOATING_POINT_LITERAL ><br>
   *
   * @param n the node to visit
   * @param argu the user argument
   */
  public void visit(final Stoichiometry n, final A argu) {
    // nodeChoice -> . %0 < INTEGER_LITERAL >
    // .......... .. | %1 < FLOATING_POINT_LITERAL >
    n.nodeChoice.accept(this, argu);
  }

}
